//! Auto-generated CRUD admin backed by [`crate::orm`].
//!
//! Build an [`Admin`] by chaining `.model::<T>()` calls, then mount it with
//! [`Admin::register`]. This attaches list / create / edit / delete routes
//! at `/admin/<admin_name>` for each model and an index page at `/admin`
//! listing every registered model.
//!
//! ## UI ownership
//!
//! The admin HTML shell, layout, forms, tables, auth pages, and error
//! states are **framework-owned**: there is no hook for a project to
//! replace these templates. Visual customisation — logo mark, project
//! display name, primary/accent colour, density — flows through the
//! [`design::Design`] config (loaded from `rustio.design.json` if
//! present). The public `templates/` + `static/` directories of a
//! generated project are for public site pages, **not** for admin
//! overrides.
//!
//! For a single-model app, [`register`] is a convenience wrapper.

use std::sync::Arc;

use bytes::Bytes;
use chrono::{DateTime, NaiveDateTime, TimeZone, Utc};
use http_body_util::{BodyExt, Full};

use crate::error::Error;
use crate::http::{Request, Response};
use crate::orm::{Db, Model};
use crate::router::Router;

// `FormData` lives in `http` and is re-exported here so that the
// `#[derive(RustioAdmin)]`-generated code referencing
// `::rustio_core::admin::FormData` continues to work.
pub use crate::http::FormData;

pub mod design;

/// The primitive types the admin + schema layers know how to render,
/// validate, and serialise.
///
/// Marked `#[non_exhaustive]` because we expect to add variants (`Uuid`,
/// `Json`, `Decimal`, `Bytes`) in later minor releases. Callers matching
/// on this enum must include a wildcard arm.
#[non_exhaustive]
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum FieldType {
    I32,
    I64,
    String,
    Bool,
    /// `chrono::DateTime<Utc>`, stored as ISO-8601 text in SQLite.
    DateTime,
}

/// Metadata about one struct field, generated by `#[derive(RustioAdmin)]`
/// and consumed by the admin renderer + the schema exporter.
///
/// `nullable` tracks whether the source field is `Option<T>`. When true:
///   - the DB column is allowed to be `NULL`;
///   - the admin form accepts an empty value and stores it as `NULL`;
///   - the schema exports it as `"nullable": true`.
#[derive(Debug, Clone, Copy)]
pub struct AdminField {
    pub name: &'static str,
    pub ty: FieldType,
    pub editable: bool,
    pub nullable: bool,
}

pub trait AdminModel: Model {
    const ADMIN_NAME: &'static str;
    const DISPLAY_NAME: &'static str;
    const FIELDS: &'static [AdminField];

    fn field_display(&self, name: &str) -> Option<String>;
    fn from_form(form: &FormData, id: Option<i64>) -> Result<Self, Error>;

    /// Singular form of the display name. Used for labels like "New X" and
    /// "Edit X". Defaults to [`DISPLAY_NAME`]; the `#[derive(RustioAdmin)]`
    /// macro generates a proper singular form.
    fn singular_name() -> &'static str {
        Self::DISPLAY_NAME
    }
}

/// Metadata about one registered admin model.
///
/// Carries everything the admin index page, the router registration,
/// and the schema exporter need — collected by [`Admin::model`] from the
/// type's `AdminModel` / `Model` impls at registration time.
///
/// `core` marks infrastructure models (currently just `User`) that the
/// schema needs to describe but that the admin router does **not**
/// expose as CRUD pages. Core models appear in `rustio.schema.json`
/// with `"core": true` but have no `/admin/<name>` routes.
#[derive(Debug, Clone)]
pub struct AdminEntry {
    pub admin_name: &'static str,
    pub display_name: &'static str,
    pub singular_name: &'static str,
    pub table: &'static str,
    pub fields: &'static [AdminField],
    pub core: bool,
}

/// Fields the built-in `User` model exposes via the schema. Kept as a
/// `const` so tests and the schema exporter reference the same source
/// of truth. `password_hash` is marked `editable: false` so no future
/// UI layer accidentally surfaces the hash in a form; `created_at`
/// mirrors the `rustio_users.created_at` column so the schema doesn't
/// under-describe the actual table shape.
pub const USER_FIELDS: &[AdminField] = &[
    AdminField {
        name: "id",
        ty: FieldType::I64,
        editable: false,
        nullable: false,
    },
    AdminField {
        name: "email",
        ty: FieldType::String,
        editable: true,
        nullable: false,
    },
    AdminField {
        name: "password_hash",
        ty: FieldType::String,
        editable: false,
        nullable: false,
    },
    AdminField {
        name: "is_active",
        ty: FieldType::Bool,
        editable: true,
        nullable: false,
    },
    AdminField {
        name: "role",
        ty: FieldType::String,
        editable: true,
        nullable: false,
    },
    AdminField {
        name: "created_at",
        ty: FieldType::DateTime,
        editable: false,
        nullable: false,
    },
];

/// Core `AdminEntry` for the built-in `User` model. Always present in
/// every project's schema; not routed by the admin in 0.4.0.
pub(crate) const USER_ENTRY: AdminEntry = AdminEntry {
    admin_name: "users",
    display_name: "Users",
    singular_name: "User",
    table: "rustio_users",
    fields: USER_FIELDS,
    core: true,
};

// ---------------------------------------------------------------------------
// Bundled CSS + icon assets
// ---------------------------------------------------------------------------

/// Framework-owned stylesheet. Bundled into the binary via `include_str!`
/// and served at `/admin/assets/admin.css` so the admin pages reference
/// it with a single `<link>`. Projects must not edit this.
const ADMIN_CSS_BUNDLE: &str = include_str!("../assets/admin.css");

// Inline Lucide SVG icon markup. Each function returns a complete
// `<svg>` element sized by the caller's CSS (16px for toolbar,
// 18px for nav, etc.). `currentColor` lets the surrounding class
// (`.rio-btn-primary`, `.rio-icon-btn.rio-danger`) drive the stroke.
fn svg(path: &str) -> String {
    format!(
        r#"<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">{path}</svg>"#
    )
}

fn icon_layers() -> String {
    svg(
        r#"<path d="M12.83 2.18a2 2 0 0 0-1.66 0L2.6 6.08a1 1 0 0 0 0 1.83l8.58 3.91a2 2 0 0 0 1.66 0l8.58-3.9a1 1 0 0 0 0-1.83Z"/><path d="M2 12a1 1 0 0 0 .58.91l8.6 3.91a2 2 0 0 0 1.65 0l8.58-3.9A1 1 0 0 0 22 12"/><path d="M2 17a1 1 0 0 0 .58.91l8.6 3.91a2 2 0 0 0 1.65 0l8.58-3.9A1 1 0 0 0 22 17"/>"#,
    )
}

fn icon_dashboard() -> String {
    svg(
        r#"<rect width="7" height="9" x="3" y="3" rx="1"/><rect width="7" height="5" x="14" y="3" rx="1"/><rect width="7" height="9" x="14" y="12" rx="1"/><rect width="7" height="5" x="3" y="16" rx="1"/>"#,
    )
}

fn icon_plus() -> String {
    svg(r#"<path d="M5 12h14"/><path d="M12 5v14"/>"#)
}

fn icon_search() -> String {
    svg(r#"<circle cx="11" cy="11" r="8"/><path d="m21 21-4.3-4.3"/>"#)
}

fn icon_pencil() -> String {
    svg(
        r#"<path d="M12 3H5a2 2 0 0 0-2 2v14a2 2 0 0 0 2 2h14a2 2 0 0 0 2-2v-7"/><path d="M18.375 2.625a1 1 0 0 1 3 3l-9.013 9.014a2 2 0 0 1-.853.505l-2.873.84a.5.5 0 0 1-.62-.62l.84-2.873a2 2 0 0 1 .506-.852z"/>"#,
    )
}

fn icon_trash() -> String {
    svg(
        r#"<path d="M3 6h18"/><path d="M19 6v14c0 1-1 2-2 2H7c-1 0-2-1-2-2V6"/><path d="M8 6V4c0-1 1-2 2-2h4c1 0 2 1 2 2v2"/><line x1="10" x2="10" y1="11" y2="17"/><line x1="14" x2="14" y1="11" y2="17"/>"#,
    )
}

fn icon_chevron_right() -> String {
    svg(r#"<polyline points="9 18 15 12 9 6"/>"#)
}

fn icon_logout() -> String {
    svg(
        r#"<path d="M9 21H5a2 2 0 0 1-2-2V5a2 2 0 0 1 2-2h4"/><polyline points="16 17 21 12 16 7"/><line x1="21" x2="9" y1="12" y2="12"/>"#,
    )
}

fn icon_shield_alert() -> String {
    svg(
        r#"<path d="M20 13c0 5-3.5 7.5-7.66 8.95a1 1 0 0 1-.67-.01C7.5 20.5 4 18 4 13V6a1 1 0 0 1 1-1c2 0 4.5-1.2 6.24-2.72a1.17 1.17 0 0 1 1.52 0C14.51 3.81 17 5 19 5a1 1 0 0 1 1 1z"/><path d="M12 8v4"/><path d="M12 16h.01"/>"#,
    )
}

fn icon_triangle_alert() -> String {
    svg(
        r#"<path d="m21.73 18-8-14a2 2 0 0 0-3.48 0l-8 14A2 2 0 0 0 4 21h16a2 2 0 0 0 1.73-3Z"/><path d="M12 9v4"/><path d="M12 17h.01"/>"#,
    )
}

fn icon_inbox() -> String {
    svg(
        r#"<polyline points="22 12 16 12 14 15 10 15 8 12 2 12"/><path d="M5.45 5.11 2 12v6a2 2 0 0 0 2 2h16a2 2 0 0 0 2-2v-6l-3.45-6.89A2 2 0 0 0 16.76 4H7.24a2 2 0 0 0-1.79 1.11z"/>"#,
    )
}

fn icon_arrow_left() -> String {
    svg(r#"<path d="m12 19-7-7 7-7"/><path d="M19 12H5"/>"#)
}

// ---------------------------------------------------------------------------
// Admin builder + route registration
// ---------------------------------------------------------------------------

type ModelRegistrar = Box<dyn FnOnce(Router, &Db, Arc<Vec<AdminEntry>>) -> Router + Send + Sync>;

/// Builder that collects admin models and mounts them with a shared
/// `/admin` index page.
pub struct Admin {
    entries: Vec<AdminEntry>,
    registrars: Vec<ModelRegistrar>,
}

impl Admin {
    pub fn new() -> Self {
        Self {
            entries: vec![USER_ENTRY.clone()],
            registrars: Vec::new(),
        }
    }

    /// Register a user-facing model on this admin.
    pub fn model<T: AdminModel>(mut self) -> Self {
        self.entries.push(AdminEntry {
            admin_name: T::ADMIN_NAME,
            display_name: T::DISPLAY_NAME,
            singular_name: T::singular_name(),
            table: T::TABLE,
            fields: T::FIELDS,
            core: false,
        });
        self.registrars.push(Box::new(|router, db, entries| {
            mount_model::<T>(router, db, entries)
        }));
        self
    }

    /// Number of user-registered models (not counting core models).
    pub fn len(&self) -> usize {
        self.entries.iter().filter(|e| !e.core).count()
    }

    pub fn is_empty(&self) -> bool {
        self.len() == 0
    }

    /// All entries, including core models. Used by the schema exporter;
    /// iterate with `.iter().filter(|e| !e.core)` when you want only
    /// user-facing models.
    pub fn entries(&self) -> &[AdminEntry] {
        &self.entries
    }

    /// Mount the admin onto a router.
    pub fn register(self, mut router: Router, db: &Db) -> Router {
        let entries = Arc::new(self.entries);

        // Static asset: framework-owned stylesheet. Cached for an hour
        // because the bytes are pinned to the compiled binary — the
        // content can only change with a redeploy.
        router = router.get("/admin/assets/admin.css", |_req, _params| async move {
            Ok::<Response, Error>(admin_css_response())
        });

        // Admin index.
        let index_entries = entries.clone();
        router = router.get("/admin", move |req, _params| {
            let entries = index_entries.clone();
            async move {
                if let Err(resp) = admin_guard(req.ctx()) {
                    return Ok(resp);
                }
                let shell = Shell::from_ctx(&entries, None, req.ctx());
                Ok::<Response, Error>(dashboard_response(shell))
            }
        });

        // Login + logout. Unauthenticated users *need* to reach
        // /admin/login; logout is CSRF-protected inside the handler.
        let login_db = db.clone();
        router = router.post("/admin/login", move |req, _params| {
            let db = login_db.clone();
            async move { handle_login(req, &db).await }
        });
        let logout_db = db.clone();
        router = router.post("/admin/logout", move |req, _params| {
            let db = logout_db.clone();
            async move { handle_logout(req, &db).await }
        });

        for registrar in self.registrars {
            router = registrar(router, db, entries.clone());
        }
        router
    }
}

impl Default for Admin {
    fn default() -> Self {
        Self::new()
    }
}

/// Convenience: mount CRUD routes and an `/admin` index for a single model.
pub fn register<T>(router: Router, db: &Db) -> Router
where
    T: AdminModel + Model,
{
    Admin::new().model::<T>().register(router, db)
}

fn mount_model<T>(mut router: Router, db: &Db, entries: Arc<Vec<AdminEntry>>) -> Router
where
    T: AdminModel + Model,
{
    let base = format!("/admin/{}", T::ADMIN_NAME);
    let create_path = format!("{base}/create");
    let edit_path = format!("{base}/:id/edit");
    let delete_path = format!("{base}/:id/delete");

    // --- list ---
    let list_db = db.clone();
    let list_entries = entries.clone();
    router = router.get(&base, move |req, _params| {
        let db = list_db.clone();
        let entries = list_entries.clone();
        async move {
            if let Err(resp) = admin_guard(req.ctx()) {
                return Ok(resp);
            }
            let shell = Shell::from_ctx(&entries, Some(T::ADMIN_NAME), req.ctx());
            let items = T::all(&db).await?;
            Ok::<Response, Error>(list_response::<T>(shell, &items))
        }
    });

    // --- create (GET + POST) ---
    let create_entries = entries.clone();
    router = router.get(&create_path, move |req, _params| {
        let entries = create_entries.clone();
        async move {
            if let Err(resp) = admin_guard(req.ctx()) {
                return Ok(resp);
            }
            let shell = Shell::from_ctx(&entries, Some(T::ADMIN_NAME), req.ctx());
            Ok::<Response, Error>(form_response::<T>(shell, FormMode::Create))
        }
    });

    let create_db = db.clone();
    router = router.post(&create_path, move |req, _params| {
        let db = create_db.clone();
        async move {
            if let Err(resp) = admin_guard(req.ctx()) {
                return Ok(resp);
            }
            let (_, body, ctx) = req.into_parts();
            let form = read_form_from_parts(body).await?;
            require_csrf(&ctx, &form)?;
            let item = T::from_form(&form, None)?;
            item.create(&db).await?;
            Ok::<Response, Error>(with_admin_headers(redirect(&format!(
                "/admin/{}",
                T::ADMIN_NAME
            ))))
        }
    });

    // --- edit (GET + POST) ---
    let edit_db = db.clone();
    let edit_entries = entries.clone();
    router = router.get(&edit_path, move |req, params| {
        let db = edit_db.clone();
        let entries = edit_entries.clone();
        async move {
            if let Err(resp) = admin_guard(req.ctx()) {
                return Ok(resp);
            }
            let id = parse_id_param(&params)?;
            let item = T::find(&db, id).await?.ok_or(Error::NotFound)?;
            let shell = Shell::from_ctx(&entries, Some(T::ADMIN_NAME), req.ctx());
            Ok::<Response, Error>(form_response::<T>(
                shell,
                FormMode::Edit { id, item: &item },
            ))
        }
    });

    let update_db = db.clone();
    router = router.post(&edit_path, move |req, params| {
        let db = update_db.clone();
        async move {
            if let Err(resp) = admin_guard(req.ctx()) {
                return Ok(resp);
            }
            let id = parse_id_param(&params)?;
            let (_, body, ctx) = req.into_parts();
            let form = read_form_from_parts(body).await?;
            require_csrf(&ctx, &form)?;
            let item = T::from_form(&form, Some(id))?;
            item.update(&db).await?;
            Ok::<Response, Error>(with_admin_headers(redirect(&format!(
                "/admin/{}",
                T::ADMIN_NAME
            ))))
        }
    });

    // --- delete: GET = confirmation page, POST = perform delete ---
    let delete_confirm_db = db.clone();
    let delete_confirm_entries = entries.clone();
    router = router.get(&delete_path, move |req, params| {
        let db = delete_confirm_db.clone();
        let entries = delete_confirm_entries.clone();
        async move {
            if let Err(resp) = admin_guard(req.ctx()) {
                return Ok(resp);
            }
            let id = parse_id_param(&params)?;
            let item = T::find(&db, id).await?.ok_or(Error::NotFound)?;
            let shell = Shell::from_ctx(&entries, Some(T::ADMIN_NAME), req.ctx());
            Ok::<Response, Error>(delete_confirmation_response::<T>(shell, id, &item))
        }
    });

    let delete_db = db.clone();
    router = router.post(&delete_path, move |req, params| {
        let db = delete_db.clone();
        async move {
            if let Err(resp) = admin_guard(req.ctx()) {
                return Ok(resp);
            }
            let id = parse_id_param(&params)?;
            let (_, body, ctx) = req.into_parts();
            let form = read_form_from_parts(body).await?;
            require_csrf(&ctx, &form)?;
            T::delete(&db, id).await?;
            Ok::<Response, Error>(with_admin_headers(redirect(&format!(
                "/admin/{}",
                T::ADMIN_NAME
            ))))
        }
    });

    router
}

fn parse_id_param(params: &crate::router::Params) -> Result<i64, Error> {
    params
        .get("id")
        .and_then(|s| s.parse::<i64>().ok())
        .ok_or_else(|| Error::BadRequest(String::from("invalid id")))
}

// ---------------------------------------------------------------------------
// Constants + context helpers
// ---------------------------------------------------------------------------

/// Maximum size of an admin form body.
pub const MAX_FORM_BODY_BYTES: usize = crate::http::MAX_REQUEST_BODY_BYTES;

/// Name of the hidden form field that carries the per-session CSRF token.
pub const CSRF_FIELD: &str = "_csrf";

fn ctx_csrf(ctx: &crate::context::Context) -> Option<&str> {
    ctx.get::<crate::auth::CsrfToken>().map(|t| t.0.as_str())
}

fn ctx_user_email(ctx: &crate::context::Context) -> Option<&str> {
    ctx.get::<crate::auth::Identity>().map(|i| i.email.as_str())
}

fn csrf_input(csrf: Option<&str>) -> String {
    match csrf {
        Some(token) if !token.is_empty() => format!(
            r#"<input type="hidden" name="{name}" value="{value}">"#,
            name = CSRF_FIELD,
            value = escape_html(token),
        ),
        _ => String::new(),
    }
}

fn require_csrf(ctx: &crate::context::Context, form: &FormData) -> Result<(), Error> {
    let expected = ctx
        .get::<crate::auth::CsrfToken>()
        .map(|t| t.0.as_str())
        .unwrap_or("");
    let provided = form.get(CSRF_FIELD).unwrap_or("");
    if !crate::auth::csrf::verify_token(expected, provided) {
        return Err(Error::Forbidden);
    }
    Ok(())
}

fn with_admin_headers(mut resp: Response) -> Response {
    use hyper::header::HeaderValue;
    let h = resp.headers_mut();
    h.insert("x-frame-options", HeaderValue::from_static("DENY"));
    h.insert(
        "x-content-type-options",
        HeaderValue::from_static("nosniff"),
    );
    h.insert("referrer-policy", HeaderValue::from_static("no-referrer"));
    if crate::auth::in_production() {
        h.insert(
            "strict-transport-security",
            HeaderValue::from_static("max-age=31536000; includeSubDomains"),
        );
    }
    resp
}

async fn read_form(req: Request) -> Result<FormData, Error> {
    let (_, body, _) = req.into_parts();
    read_form_from_parts(body).await
}

async fn read_form_from_parts(body: hyper::body::Incoming) -> Result<FormData, Error> {
    let limited = http_body_util::Limited::new(body, MAX_FORM_BODY_BYTES);
    let collected = limited.collect().await.map_err(|e| {
        if e.downcast_ref::<http_body_util::LengthLimitError>()
            .is_some()
        {
            Error::PayloadTooLarge
        } else {
            Error::BadRequest(e.to_string())
        }
    })?;
    let bytes = collected.to_bytes();
    let body_str = std::str::from_utf8(&bytes).map_err(|e| Error::BadRequest(e.to_string()))?;
    Ok(FormData::parse(body_str))
}

fn redirect(to: &str) -> Response {
    hyper::Response::builder()
        .status(303)
        .header("location", to)
        .body(Full::new(Bytes::new()))
        .expect("valid redirect")
}

fn admin_css_response() -> Response {
    use hyper::header::HeaderValue;
    let mut resp = hyper::Response::builder()
        .status(200)
        .header("content-type", "text/css; charset=utf-8")
        .header("cache-control", "public, max-age=3600")
        .body(Full::new(Bytes::from_static(ADMIN_CSS_BUNDLE.as_bytes())))
        .expect("valid css response");
    let h = resp.headers_mut();
    // Nosniff on the stylesheet too — an attacker who can upload to an
    // admin-adjacent endpoint mustn't get the browser to execute it.
    h.insert(
        "x-content-type-options",
        HeaderValue::from_static("nosniff"),
    );
    resp
}

// ---------------------------------------------------------------------------
// Shell (sidebar + topbar) — wraps every authenticated page
// ---------------------------------------------------------------------------

/// Per-request data the shell needs: registered models (for the sidebar),
/// which one is active (for highlight), the signed-in user email (for
/// the sidebar footer), and the session's CSRF token (for the logout
/// form). Cheaply constructed from a request context.
struct Shell<'a> {
    entries: &'a [AdminEntry],
    active: Option<&'a str>,
    user_email: Option<&'a str>,
    csrf: Option<&'a str>,
}

impl<'a> Shell<'a> {
    fn from_ctx(
        entries: &'a [AdminEntry],
        active: Option<&'a str>,
        ctx: &'a crate::context::Context,
    ) -> Self {
        Self {
            entries,
            active,
            user_email: ctx_user_email(ctx),
            csrf: ctx_csrf(ctx),
        }
    }
}

/// One breadcrumb segment: `(label, optional href)`. The last segment
/// is rendered as the current page (no link).
type Crumb<'a> = (&'a str, Option<&'a str>);

fn render_breadcrumbs(crumbs: &[Crumb<'_>]) -> String {
    if crumbs.is_empty() {
        return String::new();
    }
    let sep = format!(
        r#"<span class="rio-crumb-sep">{}</span>"#,
        icon_chevron_right()
    );
    let mut out = String::from(r#"<nav class="rio-breadcrumbs" aria-label="Breadcrumb">"#);
    for (i, (label, href)) in crumbs.iter().enumerate() {
        let is_last = i == crumbs.len() - 1;
        if i > 0 {
            out.push_str(&sep);
        }
        match (is_last, href) {
            (true, _) => {
                out.push_str(&format!(
                    r#"<span class="rio-crumb-current" aria-current="page">{}</span>"#,
                    escape_html(label),
                ));
            }
            (false, Some(h)) => {
                out.push_str(&format!(
                    r#"<a href="{}">{}</a>"#,
                    escape_html(h),
                    escape_html(label),
                ));
            }
            (false, None) => {
                out.push_str(&escape_html(label));
            }
        }
    }
    out.push_str("</nav>");
    out
}

fn render_sidebar(shell: &Shell<'_>) -> String {
    let design = design::Design::global();
    let user_facing: Vec<&AdminEntry> = shell.entries.iter().filter(|e| !e.core).collect();

    let mut models_html = String::new();
    if !user_facing.is_empty() {
        models_html.push_str(r#"<div class="rio-nav">"#);
        models_html.push_str(r#"<div class="rio-nav-section">Models</div>"#);
        for e in &user_facing {
            let active_cls = if shell.active == Some(e.admin_name) {
                "rio-nav-link is-active"
            } else {
                "rio-nav-link"
            };
            models_html.push_str(&format!(
                r#"<a class="{cls}" href="/admin/{name}">{icon}<span>{label}</span></a>"#,
                cls = active_cls,
                name = escape_html(e.admin_name),
                icon = icon_layers(),
                label = escape_html(e.display_name),
            ));
        }
        models_html.push_str("</div>");
    }

    let dashboard_active = if shell.active.is_none() {
        "rio-nav-link is-active"
    } else {
        "rio-nav-link"
    };

    let logout_form = if shell.csrf.is_some() {
        format!(
            r#"<form class="rio-sidebar-logout" method="post" action="/admin/logout">
{csrf}
<button type="submit">{icon}<span>Sign out</span></button>
</form>"#,
            csrf = csrf_input(shell.csrf),
            icon = icon_logout(),
        )
    } else {
        String::new()
    };

    let email = shell.user_email.unwrap_or("");
    let avatar_initial = email
        .chars()
        .next()
        .map(|c| c.to_ascii_uppercase().to_string())
        .unwrap_or_else(|| String::from("·"));

    let user_block = if shell.user_email.is_some() {
        format!(
            r#"<div class="rio-sidebar-user">
<span class="rio-avatar">{avatar}</span>
<span class="rio-user-email">{email}</span>
</div>"#,
            avatar = escape_html(&avatar_initial),
            email = escape_html(email),
        )
    } else {
        String::new()
    };

    format!(
        r#"<aside class="rio-sidebar">
<a class="rio-brand" href="/admin">
<span class="rio-brand-mark">{logo}</span>
<span class="rio-brand-meta">
<span class="rio-brand-name">{project}</span>
<span class="rio-brand-label">Admin</span>
</span>
</a>
<nav class="rio-nav">
<a class="{dash}" href="/admin">{dash_icon}<span>Dashboard</span></a>
</nav>
{models}
<div class="rio-sidebar-footer">
{user}
{logout}
</div>
</aside>"#,
        logo = escape_html(&design.logo_initial),
        project = escape_html(&design.project_name),
        dash = dashboard_active,
        dash_icon = icon_dashboard(),
        models = models_html,
        user = user_block,
        logout = logout_form,
    )
}

/// Render an authenticated shell page. Used for dashboard, list, form,
/// and delete-confirmation responses.
#[allow(clippy::too_many_arguments)]
fn render_shell_page(
    shell: &Shell<'_>,
    status: u16,
    document_title: &str,
    page_title: &str,
    page_subtitle: Option<&str>,
    breadcrumbs: &[Crumb<'_>],
    actions: &str,
    body: &str,
) -> Response {
    let design = design::Design::global();

    let sidebar = render_sidebar(shell);
    let crumbs = render_breadcrumbs(breadcrumbs);

    let env_chip = if crate::auth::in_production() {
        r#"<span class="rio-env-chip is-prod">production</span>"#.to_string()
    } else {
        r#"<span class="rio-env-chip">development</span>"#.to_string()
    };

    let subtitle_html = page_subtitle
        .map(|s| format!(r#"<p class="rio-page-subtitle">{}</p>"#, escape_html(s)))
        .unwrap_or_default();

    let actions_block = if actions.is_empty() {
        String::new()
    } else {
        format!(r#"<div class="rio-page-actions">{actions}</div>"#)
    };

    let theme_style = format!(
        "\n:root {{\n  --rio-primary: {p};\n  --rio-primary-hover: {ph};\n  --rio-accent: {a};\n  --rio-accent-hover: {ah};\n}}\n",
        p = escape_css_color(&design.primary_color),
        ph = escape_css_color(&design.primary_color),
        a = escape_css_color(&design.accent_color),
        ah = escape_css_color(&design.accent_color),
    );

    let density_class = match design.density {
        design::Density::Comfortable => "",
        design::Density::Compact => " rio-density-compact",
    };

    let body_html = format!(
        r#"<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>{doc_title} · {project}</title>
<link rel="stylesheet" href="/admin/assets/admin.css">
<style>{theme}</style>
</head>
<body class="rio-body{density}">
<div class="rio-app">
{sidebar}
<main class="rio-main">
<header class="rio-topbar">
{crumbs}
{env}
</header>
<div class="rio-page-header">
<div>
<h1 class="rio-page-title">{page_title}</h1>
{subtitle}
</div>
{actions}
</div>
{body}
</main>
</div>
</body>
</html>"#,
        doc_title = escape_html(document_title),
        project = escape_html(&design.project_name),
        theme = theme_style,
        density = density_class,
        sidebar = sidebar,
        crumbs = crumbs,
        env = env_chip,
        page_title = escape_html(page_title),
        subtitle = subtitle_html,
        actions = actions_block,
        body = body,
    );

    let resp = hyper::Response::builder()
        .status(status)
        .header("content-type", "text/html; charset=utf-8")
        .body(Full::new(Bytes::from(body_html)))
        .expect("valid response");
    with_admin_headers(resp)
}

/// Minimal sanitiser for CSS colour tokens emitted inline in a
/// `<style>` block. We reject any input containing `;`, `{`, `}`, `<`,
/// or backslash to prevent a breakout from the CSS context into another
/// attribute or the HTML parser. Returns the original string when safe,
/// or a fallback token when suspicious.
fn escape_css_color(s: &str) -> &str {
    if s.contains([';', '{', '}', '<', '\\']) {
        // Fall back to the default primary colour.
        "#0f172a"
    } else {
        s
    }
}

// ---------------------------------------------------------------------------
// Dashboard (admin index)
// ---------------------------------------------------------------------------

fn dashboard_response(shell: Shell<'_>) -> Response {
    let user_facing: Vec<&AdminEntry> = shell.entries.iter().filter(|e| !e.core).collect();

    let body = if user_facing.is_empty() {
        format!(
            r#"<div class="rio-card">
<div class="rio-empty">
<div class="rio-empty-icon">{icon}</div>
<h3>No models registered yet</h3>
<p>Register a model with <code>Admin::new().model::&lt;YourModel&gt;()</code> or scaffold a new app via <code>rustio new app &lt;name&gt;</code> to get started.</p>
</div>
</div>"#,
            icon = icon_inbox(),
        )
    } else {
        let cards: String = user_facing
            .iter()
            .map(|e| {
                format!(
                    r#"<a class="rio-model-card" href="/admin/{name}">
<div class="rio-model-card-head">
<div class="rio-model-card-icon">{icon}</div>
</div>
<p class="rio-model-name">{display}</p>
<p class="rio-model-count">Stored in <code>{table}</code></p>
<div class="rio-model-card-actions">
<span class="rio-btn rio-btn-sm rio-btn-ghost">View</span>
<span class="rio-btn rio-btn-sm rio-btn-primary">{plus}<span>Add</span></span>
</div>
</a>"#,
                    name = escape_html(e.admin_name),
                    display = escape_html(e.display_name),
                    table = escape_html(e.table),
                    icon = icon_layers(),
                    plus = icon_plus(),
                )
            })
            .collect();
        format!(r#"<div class="rio-grid">{cards}</div>"#)
    };

    render_shell_page(
        &shell,
        200,
        "Dashboard",
        "Dashboard",
        Some("Manage your data. Click a model to list, search, and edit."),
        &[],
        "",
        &body,
    )
}

// ---------------------------------------------------------------------------
// List page
// ---------------------------------------------------------------------------

fn list_response<T: AdminModel>(shell: Shell<'_>, items: &[T]) -> Response {
    let count = items.len();
    let singular = T::singular_name();
    let plural = T::DISPLAY_NAME;
    let admin_name = T::ADMIN_NAME;

    let actions = format!(
        r#"<a class="rio-btn rio-btn-primary" href="/admin/{name}/create">{icon}<span>Add {singular}</span></a>"#,
        name = escape_html(admin_name),
        singular = escape_html(singular),
        icon = icon_plus(),
    );

    let body = if items.is_empty() {
        format!(
            r#"<div class="rio-card">
<div class="rio-empty">
<div class="rio-empty-icon">{icon}</div>
<h3>No {plural} yet</h3>
<p>This model has no rows. Create the first one to get going.</p>
<a class="rio-btn rio-btn-primary" href="/admin/{name}/create">{plus}<span>Create your first {singular}</span></a>
</div>
</div>"#,
            plural = escape_html(&plural.to_lowercase()),
            icon = icon_inbox(),
            name = escape_html(admin_name),
            plus = icon_plus(),
            singular = escape_html(singular),
        )
    } else {
        let headers: String = T::FIELDS
            .iter()
            .map(|f| format!("<th>{}</th>", escape_html(f.name)))
            .collect();
        let rows: String = items
            .iter()
            .map(|item| {
                let cells: String = T::FIELDS
                    .iter()
                    .map(|f| render_cell::<T>(f, item))
                    .collect();
                let id = item.id();
                let actions = format!(
                    r#"<td class="rio-cell-actions">
<div class="rio-row-actions">
<a class="rio-icon-btn" href="/admin/{name}/{id}/edit" title="Edit" aria-label="Edit {singular}">{pencil}</a>
<a class="rio-icon-btn rio-danger" href="/admin/{name}/{id}/delete" title="Delete" aria-label="Delete {singular}">{trash}</a>
</div>
</td>"#,
                    name = escape_html(admin_name),
                    id = id,
                    singular = escape_html(singular),
                    pencil = icon_pencil(),
                    trash = icon_trash(),
                );
                format!("<tr>{cells}{actions}</tr>")
            })
            .collect();

        let count_label = if count == 1 {
            format!("1 {}", singular.to_lowercase())
        } else {
            format!("{count} {}", plural.to_lowercase())
        };

        format!(
            r#"<div class="rio-table-wrap">
<div class="rio-table-toolbar">
<div class="rio-search">
{search_icon}
<input type="search" placeholder="Search (coming soon)" aria-label="Search {plural}" disabled>
</div>
<div class="rio-count">{count_label}</div>
</div>
<table class="rio-table">
<thead><tr>{headers}<th aria-label="Actions"></th></tr></thead>
<tbody>{rows}</tbody>
</table>
</div>"#,
            search_icon = icon_search(),
            plural = escape_html(&plural.to_lowercase()),
            count_label = escape_html(&count_label),
        )
    };

    let crumbs: &[Crumb<'_>] = &[("Admin", Some("/admin")), (plural, None)];

    render_shell_page(
        &shell,
        200,
        plural,
        plural,
        Some(&format!("Browse and manage {}.", plural.to_lowercase())),
        crumbs,
        &actions,
        &body,
    )
}

/// Render one table cell for an admin list row. Adds styling classes
/// based on field type: the id column gets a monospace, muted style;
/// the first non-id String field becomes the primary-weight cell; bool
/// values render as pills; nulls render as a subtle em-dash.
fn render_cell<T: AdminModel>(f: &AdminField, item: &T) -> String {
    let value = item.field_display(f.name).unwrap_or_default();
    if f.name == "id" {
        return format!(r#"<td class="rio-cell-id">{}</td>"#, escape_html(&value));
    }
    if value.is_empty() && f.nullable {
        return r#"<td class="rio-cell-muted">—</td>"#.to_string();
    }
    if matches!(f.ty, FieldType::Bool) {
        let (cls, label) = match value.as_str() {
            "true" => ("rio-pill rio-pill-emerald", "true"),
            "false" => ("rio-pill rio-pill-slate", "false"),
            other => ("rio-pill rio-pill-slate", other),
        };
        return format!(
            r#"<td><span class="{cls}">{}</span></td>"#,
            escape_html(label)
        );
    }
    // First field after id becomes the primary-weight cell.
    let is_primary = f.name != "id"
        && T::FIELDS
            .iter()
            .find(|x| x.name != "id")
            .map(|first| first.name == f.name)
            .unwrap_or(false);
    let cls = if is_primary {
        "rio-cell-primary"
    } else {
        "rio-cell-muted"
    };
    format!(r#"<td class="{cls}">{}</td>"#, escape_html(&value))
}

// ---------------------------------------------------------------------------
// Form page (create / edit)
// ---------------------------------------------------------------------------

enum FormMode<'a, T: AdminModel> {
    Create,
    Edit { id: i64, item: &'a T },
}

fn form_response<T: AdminModel>(shell: Shell<'_>, mode: FormMode<'_, T>) -> Response {
    let plural = T::DISPLAY_NAME;
    let singular = T::singular_name();
    let admin_name = T::ADMIN_NAME;

    let (heading, doc_title, subtitle, action, back_label) = match &mode {
        FormMode::Create => (
            format!("New {singular}"),
            format!("New {singular}"),
            format!("Create a new {} record.", singular.to_lowercase()),
            format!("/admin/{admin_name}/create"),
            format!("Back to {}", plural.to_lowercase()),
        ),
        FormMode::Edit { id, .. } => (
            format!("Edit {singular}"),
            format!("Edit {singular} #{id}"),
            format!("Update this {} record.", singular.to_lowercase()),
            format!("/admin/{admin_name}/{id}/edit"),
            format!("Back to {}", plural.to_lowercase()),
        ),
    };

    let fields: String = T::FIELDS
        .iter()
        .filter(|f| f.editable)
        .map(|f| {
            render_field_block::<T>(
                f,
                match &mode {
                    FormMode::Create => None,
                    FormMode::Edit { item, .. } => Some(*item),
                },
            )
        })
        .collect();

    let meta_block = match &mode {
        FormMode::Create => String::new(),
        FormMode::Edit { id, item } => render_meta::<T>(*id, item),
    };

    let danger_zone = match &mode {
        FormMode::Create => String::new(),
        FormMode::Edit { id, .. } => format!(
            r#"<section class="rio-danger-zone">
<div class="rio-danger-copy">
<h3 class="rio-danger-title">{warn} Delete this {singular}</h3>
<p class="rio-danger-hint">This removes the record permanently. Any rows that reference it with a foreign key and <code>ON DELETE CASCADE</code> will also be deleted.</p>
</div>
<a class="rio-btn rio-btn-danger" href="/admin/{name}/{id}/delete">{trash}<span>Delete…</span></a>
</section>"#,
            warn = icon_triangle_alert(),
            singular = escape_html(&singular.to_lowercase()),
            name = escape_html(admin_name),
            id = id,
            trash = icon_trash(),
        ),
    };

    let csrf_hidden = csrf_input(shell.csrf);

    let body = format!(
        r#"{meta}
<form class="rio-card rio-form" method="post" action="{action}" autocomplete="off">
{csrf}
<div class="rio-form-section">
<h2 class="rio-form-section-title">Details</h2>
<p class="rio-form-section-hint">Fields marked optional accept an empty value.</p>
{fields}
</div>
<div class="rio-form-footer">
<a class="rio-btn rio-btn-ghost" href="/admin/{name}">{back_icon}<span>{back_label}</span></a>
<div class="rio-footer-actions">
<a class="rio-btn" href="/admin/{name}">Cancel</a>
<button class="rio-btn rio-btn-primary" type="submit">Save</button>
</div>
</div>
</form>
{danger}"#,
        meta = meta_block,
        action = escape_html(&action),
        csrf = csrf_hidden,
        fields = fields,
        name = escape_html(admin_name),
        back_icon = icon_arrow_left(),
        back_label = escape_html(&back_label),
        danger = danger_zone,
    );

    // Bind the plural href to a local `String` so the breadcrumbs
    // array can borrow into it. Without this, `format!` creates a
    // temporary that's dropped before the render call.
    let plural_href = format!("/admin/{admin_name}");
    let crumbs: Vec<Crumb<'_>> = match &mode {
        FormMode::Create => vec![
            ("Admin", Some("/admin")),
            (plural, Some(plural_href.as_str())),
            ("New", None),
        ],
        FormMode::Edit { .. } => vec![
            ("Admin", Some("/admin")),
            (plural, Some(plural_href.as_str())),
            ("Edit", None),
        ],
    };

    render_shell_page(
        &shell,
        200,
        &doc_title,
        &heading,
        Some(&subtitle),
        &crumbs,
        "",
        &body,
    )
}

/// Render a `(label, input)` block for one editable admin field.
fn render_field_block<T: AdminModel>(f: &AdminField, item: Option<&T>) -> String {
    let name = escape_html(f.name);
    let input = render_field::<T>(f, item);
    // Bool fields render as a single checkbox row for compactness.
    if matches!(f.ty, FieldType::Bool) {
        return format!(
            r#"<div class="rio-field rio-field-row-checkbox">
{input}
<label for="_{name}">{label}</label>
</div>"#,
            input = input,
            name = name,
            label = humanise(f.name),
        );
    }
    let optional_mark = if f.nullable {
        r#"<span class="rio-field-optional">optional</span>"#.to_string()
    } else {
        String::new()
    };
    let hint = field_hint(f);
    format!(
        r#"<div class="rio-field">
<label for="_{name}">{label}{optional}</label>
{input}
{hint}
</div>"#,
        name = name,
        label = humanise(f.name),
        optional = optional_mark,
        hint = hint,
    )
}

fn field_hint(f: &AdminField) -> String {
    match f.ty {
        FieldType::DateTime => r#"<p class="rio-field-hint">Interpreted as UTC.</p>"#.to_string(),
        FieldType::Bool => String::new(),
        _ => String::new(),
    }
}

/// Convert snake_case to Title Case for humans.
fn humanise(s: &str) -> String {
    let mut out = String::with_capacity(s.len());
    let mut next_upper = true;
    for ch in s.chars() {
        if ch == '_' {
            out.push(' ');
            next_upper = true;
        } else if next_upper {
            out.push(ch.to_ascii_uppercase());
            next_upper = false;
        } else {
            out.push(ch);
        }
    }
    out
}

/// Render a metadata block for the edit page: id + immutable
/// (non-editable) field values.
fn render_meta<T: AdminModel>(id: i64, item: &T) -> String {
    let mut items = vec![format!(
        r#"<div class="rio-meta-item">
<span class="rio-meta-label">ID</span>
<span class="rio-meta-value">#{id}</span>
</div>"#,
    )];

    for f in T::FIELDS.iter() {
        if f.editable || f.name == "id" {
            continue;
        }
        let value = item.field_display(f.name).unwrap_or_default();
        let shown = if value.is_empty() {
            "—".to_string()
        } else {
            value
        };
        items.push(format!(
            r#"<div class="rio-meta-item">
<span class="rio-meta-label">{label}</span>
<span class="rio-meta-value">{value}</span>
</div>"#,
            label = escape_html(&humanise(f.name)),
            value = escape_html(&shown),
        ));
    }

    format!(r#"<div class="rio-meta">{}</div>"#, items.join(""))
}

/// Render the raw input widget for an admin field. Signature preserved
/// from earlier releases because tests and downstream code depend on
/// the exact output shape (presence/absence of `required`, the
/// `type="datetime-local"` hook, `value=""` for None).
fn render_field<T: AdminModel>(f: &AdminField, item: Option<&T>) -> String {
    let current = item
        .and_then(|i| i.field_display(f.name))
        .unwrap_or_default();
    let n = escape_html(f.name);
    let v = escape_html(&current);

    let required = if !f.nullable && !matches!(f.ty, FieldType::Bool) {
        " required"
    } else {
        ""
    };

    match f.ty {
        FieldType::Bool => format!(
            r#"<input class="rio-checkbox" id="_{n}" type="checkbox" name="{n}" {checked}>"#,
            checked = if current == "true" { "checked" } else { "" },
        ),
        FieldType::I32 | FieldType::I64 => {
            format!(
                r#"<input class="rio-input" id="_{n}" type="number" name="{n}" value="{v}"{required}>"#
            )
        }
        FieldType::String => {
            format!(
                r#"<input class="rio-input" id="_{n}" type="text" name="{n}" value="{v}"{required}>"#
            )
        }
        FieldType::DateTime => {
            format!(
                r#"<input class="rio-input" id="_{n}" type="datetime-local" name="{n}" value="{v}"{required}>"#
            )
        }
    }
}

// ---------------------------------------------------------------------------
// Delete confirmation page
// ---------------------------------------------------------------------------

fn delete_confirmation_response<T: AdminModel>(shell: Shell<'_>, id: i64, item: &T) -> Response {
    let singular = T::singular_name();
    let plural = T::DISPLAY_NAME;
    let admin_name = T::ADMIN_NAME;

    // Pick a display value: the first editable String field, or fall
    // back to the id. Gives the confirmation page some context beyond
    // a bare number.
    let summary = T::FIELDS
        .iter()
        .find(|f| f.editable && matches!(f.ty, FieldType::String))
        .and_then(|f| item.field_display(f.name))
        .filter(|s| !s.is_empty())
        .unwrap_or_else(|| format!("#{id}"));

    let csrf_hidden = csrf_input(shell.csrf);

    let body = format!(
        r#"<div class="rio-card">
<div class="rio-card-body">
<div class="rio-alert rio-alert-warn">
{warn}
<div>
<strong>This action cannot be undone.</strong>
Deleting this record removes it permanently. Rows that reference it via a foreign key with <code>ON DELETE CASCADE</code> will be deleted too.
</div>
</div>
<p>You are about to delete <strong>{singular}</strong>:</p>
<div class="rio-meta">
<div class="rio-meta-item">
<span class="rio-meta-label">ID</span>
<span class="rio-meta-value">#{id}</span>
</div>
<div class="rio-meta-item">
<span class="rio-meta-label">Summary</span>
<span class="rio-meta-value">{summary}</span>
</div>
</div>
</div>
<div class="rio-form-footer">
<a class="rio-btn rio-btn-ghost" href="/admin/{name}">{back}<span>Back to {plural_lower}</span></a>
<div class="rio-footer-actions">
<a class="rio-btn" href="/admin/{name}/{id}/edit">Cancel</a>
<form method="post" action="/admin/{name}/{id}/delete" style="margin:0">
{csrf}
<button class="rio-btn rio-btn-danger" type="submit">{trash}<span>Delete {singular}</span></button>
</form>
</div>
</div>
</div>"#,
        warn = icon_triangle_alert(),
        singular = escape_html(singular),
        id = id,
        summary = escape_html(&summary),
        name = escape_html(admin_name),
        back = icon_arrow_left(),
        plural_lower = escape_html(&plural.to_lowercase()),
        csrf = csrf_hidden,
        trash = icon_trash(),
    );

    let plural_href = format!("/admin/{admin_name}");
    let crumbs: &[Crumb<'_>] = &[
        ("Admin", Some("/admin")),
        (plural, Some(&plural_href)),
        ("Delete", None),
    ];

    render_shell_page(
        &shell,
        200,
        &format!("Delete {singular}"),
        &format!("Delete {singular}?"),
        Some("Confirm you want to remove this record."),
        crumbs,
        "",
        &body,
    )
}

// ---------------------------------------------------------------------------
// Admin guard + login/forbidden auth pages
// ---------------------------------------------------------------------------

#[allow(clippy::result_large_err)]
fn admin_guard(ctx: &crate::context::Context) -> Result<(), Response> {
    match crate::auth::require_admin(ctx) {
        Ok(_) => Ok(()),
        Err(Error::Unauthorized) => Err(login_page(401, None, None)),
        Err(Error::Forbidden) => Err(forbidden_page(ctx_csrf(ctx))),
        Err(other) => Err(other.into_response()),
    }
}

/// Render the login page. Status 401 on a pure auth-gate hit; 400 on
/// missing fields; 403 on inactive account; 429 on rate-limit trip.
fn login_page(status: u16, email: Option<&str>, error: Option<&str>) -> Response {
    let design = design::Design::global();

    let error_html = match error {
        Some(msg) => format!(
            r#"<div class="rio-alert rio-alert-error">{icon}<span>{msg}</span></div>"#,
            icon = icon_triangle_alert(),
            msg = escape_html(msg),
        ),
        None => String::new(),
    };
    let email_value = email.map(escape_html).unwrap_or_default();

    let theme_style = format!(
        "\n:root {{\n  --rio-primary: {p};\n  --rio-accent: {a};\n}}\n",
        p = escape_css_color(&design.primary_color),
        a = escape_css_color(&design.accent_color),
    );

    let footer_hint = if crate::auth::in_production() {
        r#"<p class="rio-auth-footer"><strong>production</strong> · only real user accounts sign in here.</p>"#.to_string()
    } else {
        r#"<p class="rio-auth-footer">No admin user yet? Run <code>rustio user create</code> from your project directory.</p>"#.to_string()
    };

    let body = format!(
        r#"<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>Sign in · {project}</title>
<link rel="stylesheet" href="/admin/assets/admin.css">
<style>{theme}</style>
</head>
<body>
<div class="rio-auth-shell">
<div class="rio-auth-card">
<div class="rio-auth-logo">
<span class="rio-brand-mark">{logo}</span>
<span class="rio-brand-meta">
<span class="rio-brand-name">{project}</span>
<span class="rio-brand-label">Admin</span>
</span>
</div>
<h1 class="rio-auth-title">Sign in</h1>
<p class="rio-auth-subtitle">Enter your credentials to access the admin.</p>
{error}
<form method="post" action="/admin/login" autocomplete="on">
<div class="rio-field">
<label for="_email">Email</label>
<input class="rio-input" id="_email" type="email" name="email" value="{email}" autocomplete="username" autofocus required>
</div>
<div class="rio-field">
<label for="_password">Password</label>
<input class="rio-input" id="_password" type="password" name="password" autocomplete="current-password" required>
</div>
<button class="rio-btn rio-btn-primary rio-btn-block" type="submit">Sign in</button>
</form>
{footer}
</div>
</div>
</body>
</html>"#,
        project = escape_html(&design.project_name),
        theme = theme_style,
        logo = escape_html(&design.logo_initial),
        error = error_html,
        email = email_value,
        footer = footer_hint,
    );

    let resp = hyper::Response::builder()
        .status(status)
        .header("content-type", "text/html; charset=utf-8")
        .body(Full::new(Bytes::from(body)))
        .expect("valid response");
    with_admin_headers(resp)
}

fn forbidden_page(csrf: Option<&str>) -> Response {
    let design = design::Design::global();
    let csrf_hidden = csrf_input(csrf);

    let theme_style = format!(
        "\n:root {{\n  --rio-primary: {p};\n}}\n",
        p = escape_css_color(&design.primary_color),
    );

    let body = format!(
        r#"<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>403 Forbidden · {project}</title>
<link rel="stylesheet" href="/admin/assets/admin.css">
<style>{theme}</style>
</head>
<body>
<div class="rio-error-shell">
<div class="rio-error-card">
<div class="rio-error-icon">{icon}</div>
<p class="rio-error-status">403 Forbidden</p>
<h1 class="rio-error-title">You're signed in, but you don't have admin access.</h1>
<p class="rio-error-body">Ask an administrator to promote your account, or sign out and come back with different credentials.</p>
<div class="rio-error-actions">
<form method="post" action="/admin/logout" style="margin:0">
{csrf}
<button class="rio-btn" type="submit">{logout}<span>Sign out</span></button>
</form>
</div>
</div>
</div>
</body>
</html>"#,
        project = escape_html(&design.project_name),
        theme = theme_style,
        icon = icon_shield_alert(),
        csrf = csrf_hidden,
        logout = icon_logout(),
    );

    let resp = hyper::Response::builder()
        .status(403)
        .header("content-type", "text/html; charset=utf-8")
        .body(Full::new(Bytes::from(body)))
        .expect("valid response");
    with_admin_headers(resp)
}

// ---------------------------------------------------------------------------
// Session cookie builder
// ---------------------------------------------------------------------------

fn build_session_cookie(name: &str, token: &str, max_age: i64) -> String {
    build_session_cookie_impl(name, token, max_age, crate::auth::in_production())
}

fn build_session_cookie_impl(name: &str, token: &str, max_age: i64, secure: bool) -> String {
    let secure = if secure { "; Secure" } else { "" };
    format!("{name}={token}; Path=/; HttpOnly; SameSite=Strict{secure}; Max-Age={max_age}")
}

// ---------------------------------------------------------------------------
// Login / logout handlers
// ---------------------------------------------------------------------------

async fn handle_login(req: Request, db: &crate::orm::Db) -> Result<Response, Error> {
    use crate::auth;

    let peer_ip = req.peer_addr().map(|a| a.ip().to_string());

    let form = read_form(req).await?;
    let email = form.get("email").unwrap_or("").trim().to_string();
    let password = form.get("password").unwrap_or("").to_string();

    if email.is_empty() || password.is_empty() {
        return Ok(login_page(
            400,
            Some(&email),
            Some("Email and password are both required."),
        ));
    }

    let email_key = auth::normalise_email(&email);
    let rate_key = auth::LoginRateLimiter::compose_key(&email_key, peer_ip.as_deref());
    if let Err(remaining) = auth::LoginRateLimiter::global().check(&rate_key) {
        return Ok(login_page(
            429,
            Some(&email),
            Some(&format!(
                "Too many failed attempts. Try again in {}s.",
                remaining.as_secs().max(1),
            )),
        ));
    }

    let generic = "Invalid email or password.";

    let user = auth::user::find_by_email(db, &email).await?;
    let valid = match &user {
        Some(u) => auth::password::verify(&password, &u.password_hash),
        None => {
            let _ = auth::password::verify(&password, auth::dummy_password_hash());
            false
        }
    };

    if !valid {
        auth::LoginRateLimiter::global().record_failure(&rate_key);
        return Ok(login_page(401, Some(&email), Some(generic)));
    }

    let user = user.expect("valid credentials imply a found user");
    if !user.is_active {
        return Ok(login_page(
            403,
            Some(&email),
            Some("This account is inactive. Contact an administrator."),
        ));
    }

    auth::LoginRateLimiter::global().record_success(&rate_key);
    let _ = auth::session::sweep_expired(db).await;

    let session = auth::session::create(db, user.id).await?;

    let mut resp = redirect("/admin");
    let max_age = auth::SESSION_TTL_DAYS * 24 * 3600;
    crate::http::set_cookie(
        &mut resp,
        &build_session_cookie(auth::SESSION_COOKIE, &session.id, max_age),
    );
    Ok(with_admin_headers(resp))
}

async fn handle_logout(req: Request, db: &crate::orm::Db) -> Result<Response, Error> {
    use crate::auth;

    let cookie_token = req.cookie(auth::SESSION_COOKIE);
    let (_, body, ctx) = req.into_parts();
    let form = read_form_from_parts(body).await?;
    require_csrf(&ctx, &form)?;

    if let Some(token) = cookie_token {
        let _ = auth::session::delete(db, &token).await;
    }

    let mut resp = redirect("/admin");
    crate::http::set_cookie(
        &mut resp,
        &build_session_cookie(auth::SESSION_COOKIE, "", 0),
    );
    Ok(with_admin_headers(resp))
}

// ---------------------------------------------------------------------------
// DateTime parsing
// ---------------------------------------------------------------------------

/// Parse the `YYYY-MM-DDTHH:MM[:SS]` value emitted by the browser's
/// `<input type="datetime-local">` widget into a `DateTime<Utc>`.
pub fn parse_datetime_local(raw: &str) -> Result<DateTime<Utc>, String> {
    if raw.is_empty() {
        return Err(String::from("date-time value is empty"));
    }
    if raw.trim_matches(|c: char| c.is_ascii_whitespace()) != raw {
        return Err(format!("`{raw}` has surrounding whitespace"));
    }
    if raw.ends_with('Z') || raw.contains('+') || (raw.matches('-').count() > 2) {
        return Err(format!(
            "`{raw}` looks like a timezoned date-time; expected YYYY-MM-DDTHH:MM"
        ));
    }

    let parsed = NaiveDateTime::parse_from_str(raw, "%Y-%m-%dT%H:%M:%S")
        .or_else(|_| NaiveDateTime::parse_from_str(raw, "%Y-%m-%dT%H:%M"))
        .map_err(|_| format!("`{raw}` is not a valid date-time"))?;
    match Utc.from_local_datetime(&parsed) {
        chrono::LocalResult::Single(dt) => Ok(dt),
        _ => Err(format!("`{raw}` could not be interpreted as UTC")),
    }
}

fn escape_html(s: &str) -> String {
    let mut out = String::with_capacity(s.len());
    for ch in s.chars() {
        match ch {
            '&' => out.push_str("&amp;"),
            '<' => out.push_str("&lt;"),
            '>' => out.push_str("&gt;"),
            '"' => out.push_str("&quot;"),
            '\'' => out.push_str("&#39;"),
            c => out.push(c),
        }
    }
    out
}

#[cfg(test)]
mod tests {
    use super::*;
    use chrono::Timelike;

    // --- session cookie builder -----------------------------------------
    //
    // Drive both branches by passing `secure` explicitly. Avoids
    // mutating RUSTIO_ENV, which is read by tests in other modules
    // and would introduce non-determinism under parallel test runs.

    #[test]
    fn session_cookie_dev_has_no_secure_flag() {
        let c = build_session_cookie_impl("rustio_session", "TOK", 600, false);
        assert_eq!(
            c,
            "rustio_session=TOK; Path=/; HttpOnly; SameSite=Strict; Max-Age=600"
        );
        assert!(!c.contains("Secure"));
    }

    #[test]
    fn session_cookie_production_has_secure_flag() {
        let c = build_session_cookie_impl("rustio_session", "TOK", 600, true);
        assert_eq!(
            c,
            "rustio_session=TOK; Path=/; HttpOnly; SameSite=Strict; Secure; Max-Age=600"
        );
    }

    #[test]
    fn session_cookie_expiration_shape_is_stable() {
        let c = build_session_cookie_impl("rustio_session", "", 0, true);
        assert!(c.contains("rustio_session=; "));
        assert!(c.contains("HttpOnly"));
        assert!(c.contains("SameSite=Strict"));
        assert!(c.contains("Secure"));
        assert!(c.contains("Max-Age=0"));
    }

    #[test]
    fn escape_html_escapes_dangerous_chars() {
        assert_eq!(
            escape_html("<script>alert(\"xss\")</script>"),
            "&lt;script&gt;alert(&quot;xss&quot;)&lt;/script&gt;"
        );
        assert_eq!(escape_html("a & b"), "a &amp; b");
        assert_eq!(escape_html("it's"), "it&#39;s");
    }

    // --- CSS colour escaper -------------------------------------------

    #[test]
    fn escape_css_color_accepts_hex_tokens() {
        assert_eq!(escape_css_color("#0f172a"), "#0f172a");
        assert_eq!(escape_css_color("#4f46e5"), "#4f46e5");
    }

    #[test]
    fn escape_css_color_rejects_injection_attempts() {
        // Any character that could break out of the CSS value context
        // falls back to the safe default.
        assert_eq!(escape_css_color("red; } body { display:none"), "#0f172a");
        assert_eq!(escape_css_color("}</style><script>"), "#0f172a");
        assert_eq!(escape_css_color("red\\0A "), "#0f172a");
    }

    // --- DateTime parsing edge cases ------------------------------------

    #[test]
    fn parse_datetime_local_accepts_minute_precision() {
        let dt = parse_datetime_local("2026-04-18T10:12").unwrap();
        assert_eq!(dt.to_rfc3339(), "2026-04-18T10:12:00+00:00");
        assert!(dt.to_rfc3339().ends_with("+00:00"));
    }

    #[test]
    fn parse_datetime_local_accepts_second_precision() {
        let dt = parse_datetime_local("2026-04-18T10:12:33").unwrap();
        assert_eq!(dt.to_rfc3339(), "2026-04-18T10:12:33+00:00");
    }

    #[test]
    fn parse_datetime_local_rejects_empty_string() {
        assert!(parse_datetime_local("").is_err());
    }

    #[test]
    fn parse_datetime_local_rejects_free_text() {
        assert!(parse_datetime_local("tomorrow at noon").is_err());
    }

    #[test]
    fn parse_datetime_local_rejects_partial_date() {
        assert!(parse_datetime_local("2026-04-18").is_err());
    }

    #[test]
    fn parse_datetime_local_rejects_out_of_range_date() {
        assert!(parse_datetime_local("2026-13-01T00:00").is_err());
        assert!(parse_datetime_local("2026-04-31T00:00").is_err());
    }

    #[test]
    fn parse_datetime_local_rejects_out_of_range_time() {
        assert!(parse_datetime_local("2026-04-18T25:00").is_err());
        assert!(parse_datetime_local("2026-04-18T10:99").is_err());
    }

    #[test]
    fn parse_datetime_local_rejects_surrounding_whitespace() {
        assert!(parse_datetime_local(" 2026-04-18T10:12").is_err());
        assert!(parse_datetime_local("2026-04-18T10:12 ").is_err());
    }

    #[test]
    fn parse_datetime_local_rejects_timezone_suffix() {
        assert!(parse_datetime_local("2026-04-18T10:12Z").is_err());
        assert!(parse_datetime_local("2026-04-18T10:12:00+00:00").is_err());
    }

    // --- Admin rendering of field widgets --------------------------------

    struct Widgety;
    impl crate::orm::Model for Widgety {
        const TABLE: &'static str = "widgety";
        const COLUMNS: &'static [&'static str] = &["id"];
        const INSERT_COLUMNS: &'static [&'static str] = &[];
        fn id(&self) -> i64 {
            0
        }
        fn from_row(_: crate::orm::Row<'_>) -> Result<Self, Error> {
            unimplemented!()
        }
        fn insert_values(&self) -> Vec<crate::orm::Value> {
            Vec::new()
        }
    }
    impl AdminModel for Widgety {
        const ADMIN_NAME: &'static str = "widgety";
        const DISPLAY_NAME: &'static str = "Widgety";
        const FIELDS: &'static [AdminField] = &[];
        fn field_display(&self, name: &str) -> Option<String> {
            match name {
                "filled" => Some(String::from("2026-04-18T10:12")),
                "empty" => Some(String::new()),
                _ => None,
            }
        }
        fn from_form(_: &FormData, _: Option<i64>) -> Result<Self, Error> {
            unimplemented!()
        }
    }

    fn string_field(name: &'static str, nullable: bool) -> AdminField {
        AdminField {
            name,
            ty: FieldType::String,
            editable: true,
            nullable,
        }
    }

    fn datetime_field(name: &'static str, nullable: bool) -> AdminField {
        AdminField {
            name,
            ty: FieldType::DateTime,
            editable: true,
            nullable,
        }
    }

    #[test]
    fn nullable_string_field_omits_required_attribute() {
        let f = string_field("note", true);
        let html = render_field::<Widgety>(&f, None);
        assert!(!html.contains("required"), "html was: {html}");
    }

    #[test]
    fn non_nullable_string_field_marks_required() {
        let f = string_field("title", false);
        let html = render_field::<Widgety>(&f, None);
        assert!(html.contains("required"), "html was: {html}");
    }

    #[test]
    fn bool_field_never_marks_required() {
        let f = AdminField {
            name: "flag",
            ty: FieldType::Bool,
            editable: true,
            nullable: false,
        };
        let html = render_field::<Widgety>(&f, None);
        assert!(!html.contains("required"), "html was: {html}");
    }

    #[test]
    fn datetime_field_uses_datetime_local_input() {
        let f = datetime_field("starts_at", false);
        let html = render_field::<Widgety>(&f, None);
        assert!(
            html.contains(r#"type="datetime-local""#),
            "html was: {html}"
        );
    }

    #[test]
    fn datetime_field_renders_existing_value() {
        let f = datetime_field("filled", true);
        let html = render_field::<Widgety>(&f, Some(&Widgety));
        assert!(
            html.contains(r#"value="2026-04-18T10:12""#),
            "html was: {html}"
        );
    }

    #[test]
    fn nullable_field_with_none_value_does_not_panic() {
        let f = string_field("empty", true);
        let html = render_field::<Widgety>(&f, Some(&Widgety));
        assert!(html.contains(r#"value="""#));
        assert!(!html.contains("required"));
    }

    #[test]
    fn field_display_returning_none_renders_empty_value() {
        let f = string_field("unknown_field", false);
        let html = render_field::<Widgety>(&f, Some(&Widgety));
        assert!(html.contains(r#"value="""#));
    }

    #[test]
    fn parse_datetime_local_enforces_utc_for_every_valid_input() {
        let inputs = [
            "2000-01-01T00:00",
            "2026-04-18T10:12",
            "2026-04-18T10:12:33",
            "2099-12-31T23:59",
        ];
        for raw in inputs {
            let dt = parse_datetime_local(raw).unwrap_or_else(|e| panic!("`{raw}`: {e}"));
            assert!(
                dt.to_rfc3339().ends_with("+00:00"),
                "non-UTC offset in output for `{raw}`: {}",
                dt.to_rfc3339(),
            );
            assert!(
                dt.nanosecond() == 0,
                "unexpected sub-second part for `{raw}`"
            );
        }
    }

    // --- humanise helper ---

    #[test]
    fn humanise_converts_snake_case_to_title_case() {
        assert_eq!(humanise("title"), "Title");
        assert_eq!(humanise("is_active"), "Is Active");
        assert_eq!(humanise("created_at"), "Created At");
        assert_eq!(humanise("assigned_to"), "Assigned To");
    }
}
