//! Auto-generated CRUD admin backed by [`crate::orm`].
//!
//! Build an [`Admin`] by chaining `.model::<T>()` calls, then mount it with
//! [`Admin::register`]. This attaches list / create / edit / delete routes
//! at `/admin/<admin_name>` for each model and an index page at `/admin`
//! listing every registered model.
//!
//! For a single-model app, [`register`] is a convenience wrapper.

use std::sync::Arc;

use bytes::Bytes;
use chrono::{DateTime, NaiveDateTime, TimeZone, Utc};
use http_body_util::{BodyExt, Full};

use crate::error::Error;
use crate::http::{html, Request, Response};
use crate::orm::{Db, Model};
use crate::router::Router;

// `FormData` lives in `http` and is re-exported here so that the
// `#[derive(RustioAdmin)]`-generated code referencing
// `::rustio_core::admin::FormData` continues to work.
pub use crate::http::FormData;

/// The primitive types the admin + schema layers know how to render,
/// validate, and serialise.
///
/// Marked `#[non_exhaustive]` because we expect to add variants (`Uuid`,
/// `Json`, `Decimal`, `Bytes`) in later minor releases. Callers matching
/// on this enum must include a wildcard arm.
#[non_exhaustive]
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum FieldType {
    I32,
    I64,
    String,
    Bool,
    /// `chrono::DateTime<Utc>`, stored as ISO-8601 text in SQLite.
    DateTime,
}

/// Metadata about one struct field, generated by `#[derive(RustioAdmin)]`
/// and consumed by the admin renderer + the schema exporter.
///
/// `nullable` tracks whether the source field is `Option<T>`. When true:
///   - the DB column is allowed to be `NULL`;
///   - the admin form accepts an empty value and stores it as `NULL`;
///   - the schema exports it as `"nullable": true`.
#[derive(Debug, Clone, Copy)]
pub struct AdminField {
    pub name: &'static str,
    pub ty: FieldType,
    pub editable: bool,
    pub nullable: bool,
}

pub trait AdminModel: Model {
    const ADMIN_NAME: &'static str;
    const DISPLAY_NAME: &'static str;
    const FIELDS: &'static [AdminField];

    fn field_display(&self, name: &str) -> Option<String>;
    fn from_form(form: &FormData, id: Option<i64>) -> Result<Self, Error>;

    /// Singular form of the display name. Used for labels like "New X" and
    /// "Edit X". Defaults to [`DISPLAY_NAME`]; the `#[derive(RustioAdmin)]`
    /// macro generates a proper singular form.
    fn singular_name() -> &'static str {
        Self::DISPLAY_NAME
    }
}

/// Metadata about one registered admin model.
///
/// Carries everything the admin index page, the router registration,
/// and the schema exporter need — collected by [`Admin::model`] from the
/// type's `AdminModel` / `Model` impls at registration time.
///
/// `core` marks infrastructure models (currently just `User`) that the
/// schema needs to describe but that the admin router does **not**
/// expose as CRUD pages. Core models appear in `rustio.schema.json`
/// with `"core": true` but have no `/admin/<name>` routes.
#[derive(Debug, Clone)]
pub struct AdminEntry {
    pub admin_name: &'static str,
    pub display_name: &'static str,
    pub singular_name: &'static str,
    pub table: &'static str,
    pub fields: &'static [AdminField],
    pub core: bool,
}

/// Fields the built-in `User` model exposes via the schema. Kept as a
/// `const` so tests and the schema exporter reference the same source
/// of truth. `password_hash` is marked `editable: false` so no future
/// UI layer accidentally surfaces the hash in a form.
pub const USER_FIELDS: &[AdminField] = &[
    AdminField {
        name: "id",
        ty: FieldType::I64,
        editable: false,
        nullable: false,
    },
    AdminField {
        name: "email",
        ty: FieldType::String,
        editable: true,
        nullable: false,
    },
    AdminField {
        name: "password_hash",
        ty: FieldType::String,
        editable: false,
        nullable: false,
    },
    AdminField {
        name: "is_active",
        ty: FieldType::Bool,
        editable: true,
        nullable: false,
    },
    AdminField {
        name: "role",
        ty: FieldType::String,
        editable: true,
        nullable: false,
    },
];

/// Core `AdminEntry` for the built-in `User` model. Always present in
/// every project's schema; not routed by the admin in 0.4.0.
pub(crate) const USER_ENTRY: AdminEntry = AdminEntry {
    admin_name: "users",
    display_name: "Users",
    singular_name: "User",
    table: "rustio_users",
    fields: USER_FIELDS,
    core: true,
};

type ModelRegistrar = Box<dyn FnOnce(Router, &Db) -> Router + Send + Sync>;

/// Builder that collects admin models and mounts them with a shared
/// `/admin` index page.
///
/// ```no_run
/// use rustio_core::admin::Admin;
/// # use rustio_core::{Db, Router};
/// # fn demo(router: Router, db: &Db) -> Router {
/// # struct Post; struct User;
/// # impl rustio_core::Model for Post {
/// #   const TABLE: &'static str = "posts";
/// #   const COLUMNS: &'static [&'static str] = &[];
/// #   const INSERT_COLUMNS: &'static [&'static str] = &[];
/// #   fn id(&self) -> i64 { 0 }
/// #   fn from_row(_: rustio_core::Row<'_>) -> Result<Self, rustio_core::Error> { unimplemented!() }
/// #   fn insert_values(&self) -> Vec<rustio_core::Value> { vec![] }
/// # }
/// # impl rustio_core::Model for User {
/// #   const TABLE: &'static str = "users";
/// #   const COLUMNS: &'static [&'static str] = &[];
/// #   const INSERT_COLUMNS: &'static [&'static str] = &[];
/// #   fn id(&self) -> i64 { 0 }
/// #   fn from_row(_: rustio_core::Row<'_>) -> Result<Self, rustio_core::Error> { unimplemented!() }
/// #   fn insert_values(&self) -> Vec<rustio_core::Value> { vec![] }
/// # }
/// # impl rustio_core::admin::AdminModel for Post {
/// #   const ADMIN_NAME: &'static str = "posts"; const DISPLAY_NAME: &'static str = "Posts";
/// #   const FIELDS: &'static [rustio_core::admin::AdminField] = &[];
/// #   fn field_display(&self, _: &str) -> Option<String> { None }
/// #   fn from_form(_: &rustio_core::admin::FormData, _: Option<i64>) -> Result<Self, rustio_core::Error> { unimplemented!() }
/// # }
/// # impl rustio_core::admin::AdminModel for User {
/// #   const ADMIN_NAME: &'static str = "users"; const DISPLAY_NAME: &'static str = "Users";
/// #   const FIELDS: &'static [rustio_core::admin::AdminField] = &[];
/// #   fn field_display(&self, _: &str) -> Option<String> { None }
/// #   fn from_form(_: &rustio_core::admin::FormData, _: Option<i64>) -> Result<Self, rustio_core::Error> { unimplemented!() }
/// # }
/// Admin::new()
///     .model::<Post>()
///     .model::<User>()
///     .register(router, db)
/// # }
/// ```
pub struct Admin {
    entries: Vec<AdminEntry>,
    registrars: Vec<ModelRegistrar>,
}

impl Admin {
    pub fn new() -> Self {
        // Seed the core `User` entry unconditionally. It's infrastructure,
        // not an application choice — every project's schema includes
        // it and consumers rely on that invariant.
        Self {
            entries: vec![USER_ENTRY.clone()],
            registrars: Vec::new(),
        }
    }

    /// Register a user-facing model on this admin. Adds its metadata
    /// to the `/admin` index and queues its CRUD routes for mounting.
    /// Core models (like `User`) are registered by `Admin::new` itself
    /// and are not passed through this method.
    pub fn model<T: AdminModel>(mut self) -> Self {
        self.entries.push(AdminEntry {
            admin_name: T::ADMIN_NAME,
            display_name: T::DISPLAY_NAME,
            singular_name: T::singular_name(),
            table: T::TABLE,
            fields: T::FIELDS,
            core: false,
        });
        self.registrars
            .push(Box::new(|router, db| mount_model::<T>(router, db)));
        self
    }

    /// Number of user-registered models (i.e. not counting built-in
    /// core models like `User`). The `/admin` index uses this to decide
    /// whether to show the "no models registered yet" placeholder.
    pub fn len(&self) -> usize {
        self.entries.iter().filter(|e| !e.core).count()
    }

    pub fn is_empty(&self) -> bool {
        self.len() == 0
    }

    /// All entries, including core models. Consumed by the schema
    /// exporter; iterate with `.iter().filter(|e| !e.core)` when you
    /// want only user-facing models.
    pub fn entries(&self) -> &[AdminEntry] {
        &self.entries
    }

    /// Mount the admin onto a router: installs `/admin` (index) and
    /// CRUD routes for every registered model. Admin-only; handlers
    /// return 401/403 via [`require_admin`].
    pub fn register(self, mut router: Router, db: &Db) -> Router {
        let entries = Arc::new(self.entries);
        let index_entries = entries.clone();
        router = router.get("/admin", move |req, _params| {
            let entries = index_entries.clone();
            async move {
                if let Err(resp) = admin_guard(req.ctx()) {
                    return Ok(resp);
                }
                Ok::<Response, Error>(html(admin_layout("Admin", &index_page(&entries))))
            }
        });

        // Login + logout routes. These run without admin_guard: unauthenticated
        // users *need* to reach /admin/login, and logout should work from any
        // state (idempotent cookie expiry). Both capture `Db` so the login
        // path can verify credentials and create a session, and the logout
        // path can delete the session server-side — not just expire the
        // cookie client-side.
        let login_db = db.clone();
        router = router.post("/admin/login", move |req, _params| {
            let db = login_db.clone();
            async move { handle_login(req, &db).await }
        });
        let logout_db = db.clone();
        router = router.post("/admin/logout", move |req, _params| {
            let db = logout_db.clone();
            async move { handle_logout(req, &db).await }
        });

        for registrar in self.registrars {
            router = registrar(router, db);
        }
        router
    }
}

impl Default for Admin {
    fn default() -> Self {
        Self::new()
    }
}

/// Convenience: mount CRUD routes and an `/admin` index for a single model.
/// Equivalent to `Admin::new().model::<T>().register(router, db)`.
pub fn register<T>(router: Router, db: &Db) -> Router
where
    T: AdminModel + Model,
{
    Admin::new().model::<T>().register(router, db)
}

fn mount_model<T>(mut router: Router, db: &Db) -> Router
where
    T: AdminModel + Model,
{
    let base = format!("/admin/{}", T::ADMIN_NAME);
    let create_path = format!("{base}/create");
    let edit_path = format!("{base}/:id/edit");
    let delete_path = format!("{base}/:id/delete");

    let list_db = db.clone();
    router = router.get(&base, move |req, _params| {
        let db = list_db.clone();
        async move {
            if let Err(resp) = admin_guard(req.ctx()) {
                return Ok(resp);
            }
            let items = T::all(&db).await?;
            Ok::<Response, Error>(html(admin_layout(T::DISPLAY_NAME, &list_page::<T>(&items))))
        }
    });

    router = router.get(&create_path, |req, _params| async move {
        if let Err(resp) = admin_guard(req.ctx()) {
            return Ok(resp);
        }
        Ok::<Response, Error>(html(admin_layout(
            &format!("New {}", T::DISPLAY_NAME),
            &form_page::<T>(None, &format!("/admin/{}/create", T::ADMIN_NAME)),
        )))
    });

    let create_db = db.clone();
    router = router.post(&create_path, move |req, _params| {
        let db = create_db.clone();
        async move {
            if let Err(resp) = admin_guard(req.ctx()) {
                return Ok(resp);
            }
            let form = read_form(req).await?;
            let item = T::from_form(&form, None)?;
            item.create(&db).await?;
            Ok::<Response, Error>(redirect(&format!("/admin/{}", T::ADMIN_NAME)))
        }
    });

    let edit_db = db.clone();
    router = router.get(&edit_path, move |req, params| {
        let db = edit_db.clone();
        async move {
            if let Err(resp) = admin_guard(req.ctx()) {
                return Ok(resp);
            }
            let id = parse_id_param(&params)?;
            let item = T::find(&db, id).await?.ok_or(Error::NotFound)?;
            Ok::<Response, Error>(html(admin_layout(
                &format!("Edit {}", T::DISPLAY_NAME),
                &form_page::<T>(
                    Some(&item),
                    &format!("/admin/{}/{}/edit", T::ADMIN_NAME, id),
                ),
            )))
        }
    });

    let update_db = db.clone();
    router = router.post(&edit_path, move |req, params| {
        let db = update_db.clone();
        async move {
            if let Err(resp) = admin_guard(req.ctx()) {
                return Ok(resp);
            }
            let id = parse_id_param(&params)?;
            let form = read_form(req).await?;
            let item = T::from_form(&form, Some(id))?;
            item.update(&db).await?;
            Ok::<Response, Error>(redirect(&format!("/admin/{}", T::ADMIN_NAME)))
        }
    });

    let delete_db = db.clone();
    router = router.post(&delete_path, move |req, params| {
        let db = delete_db.clone();
        async move {
            if let Err(resp) = admin_guard(req.ctx()) {
                return Ok(resp);
            }
            let id = parse_id_param(&params)?;
            T::delete(&db, id).await?;
            Ok::<Response, Error>(redirect(&format!("/admin/{}", T::ADMIN_NAME)))
        }
    });

    router
}

fn parse_id_param(params: &crate::router::Params) -> Result<i64, Error> {
    params
        .get("id")
        .and_then(|s| s.parse::<i64>().ok())
        .ok_or_else(|| Error::BadRequest(String::from("invalid id")))
}

/// Maximum size of an admin form body. Two megabytes is generous for any
/// realistic admin submission (long text, a few small fields) and still
/// tight enough that an attacker can't exhaust memory with one POST.
///
/// Kept as a `pub const` so projects can compare against it in logs or
/// custom handlers; changing the value is a conscious choice, not a knob.
pub const MAX_FORM_BODY_BYTES: usize = 2 * 1024 * 1024;

/// Read a form body with [`MAX_FORM_BODY_BYTES`] enforced during
/// collection. An oversized body surfaces as [`Error::PayloadTooLarge`]
/// before it's ever buffered into memory — [`Limited`] streams through
/// and errors the moment the byte budget runs out.
async fn read_form(req: Request) -> Result<FormData, Error> {
    let (_, body, _) = req.into_parts();
    let limited = http_body_util::Limited::new(body, MAX_FORM_BODY_BYTES);
    let collected = limited.collect().await.map_err(|e| {
        if e.downcast_ref::<http_body_util::LengthLimitError>()
            .is_some()
        {
            Error::PayloadTooLarge
        } else {
            Error::BadRequest(e.to_string())
        }
    })?;
    let bytes = collected.to_bytes();
    let body_str = std::str::from_utf8(&bytes).map_err(|e| Error::BadRequest(e.to_string()))?;
    Ok(FormData::parse(body_str))
}

fn redirect(to: &str) -> Response {
    hyper::Response::builder()
        .status(303)
        .header("location", to)
        .body(Full::new(Bytes::new()))
        .expect("valid redirect")
}

fn admin_layout(title: &str, content: &str) -> String {
    format!(
        r#"<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>{title} — RustIO Admin</title>
<style>{css}</style>
</head>
<body>
<header>
<h1><a href="/admin">RustIO Admin</a></h1>
<form method="post" action="/admin/logout" class="header-logout">
<button type="submit">Sign out</button>
</form>
</header>
<main>{content}</main>
</body>
</html>"#,
        title = escape_html(title),
        css = ADMIN_CSS,
        content = content,
    )
}

fn index_page(entries: &[AdminEntry]) -> String {
    // Core models (built-in User) appear in the schema but not in the
    // index — they have no routed CRUD page in 0.4.0.
    let user_facing: Vec<&AdminEntry> = entries.iter().filter(|e| !e.core).collect();
    if user_facing.is_empty() {
        return String::from(
            r#"<h2>Admin</h2>
<p class="empty">No models are registered. Add one with
<code>Admin::new().model::&lt;YourModel&gt;()</code> or scaffold an app
via <code>rustio new app &lt;name&gt;</code>.</p>"#,
        );
    }
    let rows: String = user_facing
        .iter()
        .map(|e| {
            format!(
                r#"<li><a href="/admin/{name}"><span class="label">{display}</span><span class="path">/admin/{name}</span></a></li>"#,
                name = escape_html(e.admin_name),
                display = escape_html(e.display_name),
            )
        })
        .collect();
    format!(
        r#"<h2>Admin</h2>
<ul class="admin-index">{rows}</ul>"#
    )
}

fn list_page<T: AdminModel>(items: &[T]) -> String {
    let headers: String = T::FIELDS
        .iter()
        .map(|f| format!("<th>{}</th>", escape_html(f.name)))
        .collect();
    let rows: String = items
        .iter()
        .map(|item| {
            let cells: String = T::FIELDS
                .iter()
                .map(|f| {
                    let v = item.field_display(f.name).unwrap_or_default();
                    format!("<td>{}</td>", escape_html(&v))
                })
                .collect();
            let id = item.id();
            let actions = format!(
                r#"<td class="actions">
<a href="/admin/{name}/{id}/edit">edit</a>
<form method="post" action="/admin/{name}/{id}/delete">
<button type="submit" class="danger">delete</button>
</form>
</td>"#,
                name = T::ADMIN_NAME,
                id = id,
            );
            format!("<tr>{cells}{actions}</tr>")
        })
        .collect();

    format!(
        r#"<div class="toolbar">
<h2>{title}</h2>
<a class="button" href="/admin/{name}/create">New {singular}</a>
</div>
<table>
<thead><tr>{headers}<th>actions</th></tr></thead>
<tbody>{rows}</tbody>
</table>"#,
        title = escape_html(T::DISPLAY_NAME),
        singular = escape_html(T::singular_name()),
        name = T::ADMIN_NAME,
    )
}

fn form_page<T: AdminModel>(item: Option<&T>, action: &str) -> String {
    let fields: String = T::FIELDS
        .iter()
        .filter(|f| f.editable)
        .map(|f| render_field::<T>(f, item))
        .collect();
    let heading = if item.is_some() {
        format!("Edit {}", T::singular_name())
    } else {
        format!("New {}", T::singular_name())
    };
    format!(
        r#"<h2>{heading}</h2>
<form method="post" action="{action}">
{fields}
<div class="form-actions">
<button type="submit">Save</button>
<a class="cancel" href="/admin/{name}">Cancel</a>
</div>
</form>"#,
        heading = escape_html(&heading),
        action = escape_html(action),
        name = T::ADMIN_NAME,
    )
}

fn render_field<T: AdminModel>(f: &AdminField, item: Option<&T>) -> String {
    let current = item
        .and_then(|i| i.field_display(f.name))
        .unwrap_or_default();
    let n = escape_html(f.name);
    let v = escape_html(&current);

    // Non-nullable non-bool inputs are marked `required` so the browser
    // enforces presence before submission. `bool` uses checkbox semantics
    // (absent = false), so `required` would make no sense.
    let required = if !f.nullable && !matches!(f.ty, FieldType::Bool) {
        " required"
    } else {
        ""
    };

    let input = match f.ty {
        FieldType::Bool => format!(
            r#"<input type="checkbox" name="{n}" {checked}>"#,
            checked = if current == "true" { "checked" } else { "" },
        ),
        FieldType::I32 | FieldType::I64 => {
            format!(r#"<input type="number" name="{n}" value="{v}"{required}>"#)
        }
        FieldType::String => {
            format!(r#"<input type="text" name="{n}" value="{v}"{required}>"#)
        }
        // `datetime-local` renders a browser-native date/time picker. The
        // value format is `YYYY-MM-DDTHH:MM`, which our parser accepts on
        // submission and our display code emits.
        FieldType::DateTime => {
            format!(r#"<input type="datetime-local" name="{n}" value="{v}"{required}>"#)
        }
    };
    format!(r#"<label><span>{label}</span>{input}</label>"#, label = n)
}

/// Gate every admin request behind [`require_admin`], but convert the
/// resulting `Error::Unauthorized` / `Error::Forbidden` into a friendly
/// HTML response instead of the default `text/plain` body.
///
/// Returns `Ok(())` when the caller is admin and should continue.
/// Returns `Err(Response)` with a ready-made HTML error page otherwise.
//
// `Response` is moderately large; clippy's `result_large_err` would
// rather we box it. Each call site only constructs one per request and
// the call count per request is at most one, so the nominal size cost
// is irrelevant — boxing would only add noise.
#[allow(clippy::result_large_err)]
fn admin_guard(ctx: &crate::context::Context) -> Result<(), Response> {
    // 401 renders a login form (so browser users can actually sign in).
    // 403 renders a static "forbidden" page (the user is authenticated
    // but not admin — there's nothing to type into a form that would
    // change that).
    match crate::auth::require_admin(ctx) {
        Ok(_) => Ok(()),
        Err(Error::Unauthorized) => Err(login_page(401, None, None)),
        Err(Error::Forbidden) => Err(forbidden_page()),
        Err(other) => Err(other.into_response()),
    }
}

/// Render the login page. Status is 401 on a pure auth-gate hit and
/// 400 on failed submissions (with `error` set to an explanation).
///
/// The form is always shown — unauthenticated users need somewhere to
/// sign in. `email` is prefilled on failed submissions so the user
/// doesn't have to retype it; the password field never is.
fn login_page(status: u16, email: Option<&str>, error: Option<&str>) -> Response {
    let error_html = match error {
        Some(msg) => format!(r#"<p class="error">{}</p>"#, escape_html(msg)),
        None => String::new(),
    };
    let email_value = email.map(escape_html).unwrap_or_default();

    let body = format!(
        r#"<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>Sign in — RustIO Admin</title>
<style>{css}</style>
</head>
<body>
<header><h1><a href="/admin">RustIO Admin</a></h1></header>
<main class="auth-card">
<h2>Sign in</h2>
<form method="post" action="/admin/login" autocomplete="on">
<label><span>Email</span>
<input type="email" name="email" value="{email_value}" autocomplete="username" autofocus required>
</label>
<label><span>Password</span>
<input type="password" name="password" autocomplete="current-password" required>
</label>
{error}
<button type="submit">Sign in</button>
</form>
<p class="hint">No admin user yet? Run <code>rustio user create</code> from your project directory.</p>
</main>
</body>
</html>"#,
        css = ADMIN_CSS,
        email_value = email_value,
        error = error_html,
    );

    hyper::Response::builder()
        .status(status)
        .header("content-type", "text/html; charset=utf-8")
        .body(Full::new(Bytes::from(body)))
        .expect("valid response")
}

fn forbidden_page() -> Response {
    let body = format!(
        r#"<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>403 Forbidden — RustIO Admin</title>
<style>{css}</style>
</head>
<body>
<header><h1><a href="/admin">RustIO Admin</a></h1></header>
<main class="auth-error">
<div class="status">403</div>
<p class="heading">Forbidden</p>
<p class="hint">You are signed in but your account isn't an admin.</p>
<form method="post" action="/admin/logout" class="inline">
<button type="submit" class="secondary">Sign out</button>
</form>
</main>
</body>
</html>"#,
        css = ADMIN_CSS,
    );

    hyper::Response::builder()
        .status(403)
        .header("content-type", "text/html; charset=utf-8")
        .body(Full::new(Bytes::from(body)))
        .expect("valid response")
}

/// `POST /admin/login` — authenticate email + password, create a
/// session row, and set the session cookie.
///
/// Failure behaviour is deliberately narrow:
/// - invalid email *or* wrong password → identical generic message
///   ("invalid email or password"). This prevents user enumeration via
///   the response text.
/// - inactive user → explicit message. An administrator has already
///   decided this account should not log in; telling the owner so
///   isn't a leak.
/// - missing fields → 400 with a targeted message.
///
/// On success: a cryptographically random session row is inserted, a
/// `HttpOnly; SameSite=Strict` cookie carries the token, and the
/// response is a 303 redirect to `/admin`.
async fn handle_login(req: Request, db: &crate::orm::Db) -> Result<Response, Error> {
    use crate::auth;

    let form = read_form(req).await?;
    let email = form.get("email").unwrap_or("").trim().to_string();
    let password = form.get("password").unwrap_or("").to_string();

    if email.is_empty() || password.is_empty() {
        return Ok(login_page(
            400,
            Some(&email),
            Some("Email and password are both required."),
        ));
    }

    // One generic error for both "no such user" and "wrong password"
    // so a caller can't probe which emails exist.
    let generic = "Invalid email or password.";

    let user = match auth::user::find_by_email(db, &email).await? {
        Some(u) => u,
        None => return Ok(login_page(401, Some(&email), Some(generic))),
    };

    if !auth::password::verify(&password, &user.password_hash) {
        return Ok(login_page(401, Some(&email), Some(generic)));
    }

    if !user.is_active {
        return Ok(login_page(
            403,
            Some(&email),
            Some("This account is inactive. Contact an administrator."),
        ));
    }

    let session = auth::session::create(db, user.id).await?;

    // HttpOnly: JS can't read the token (XSS hardening).
    // SameSite=Strict: cross-site navigations don't send it (CSRF
    // hardening). Max-Age matches the DB expiry so the browser drops
    // the cookie at the same moment the server refuses it.
    let mut resp = redirect("/admin");
    let max_age = auth::SESSION_TTL_DAYS * 24 * 3600;
    crate::http::set_cookie(
        &mut resp,
        &format!(
            "{name}={token}; Path=/; HttpOnly; SameSite=Strict; Max-Age={max_age}",
            name = auth::SESSION_COOKIE,
            token = session.id,
        ),
    );
    Ok(resp)
}

/// `POST /admin/logout` — delete the server-side session row and
/// expire the cookie. Idempotent: logging out without being logged in
/// is not an error.
async fn handle_logout(req: Request, db: &crate::orm::Db) -> Result<Response, Error> {
    use crate::auth;

    if let Some(token) = req.cookie(auth::SESSION_COOKIE) {
        // Best-effort: a DB hiccup during logout shouldn't block the
        // user from getting their cookie cleared. The cookie expiry
        // below runs regardless.
        let _ = auth::session::delete(db, &token).await;
    }

    let mut resp = redirect("/admin");
    crate::http::set_cookie(
        &mut resp,
        &format!(
            "{name}=; Path=/; HttpOnly; SameSite=Strict; Max-Age=0",
            name = auth::SESSION_COOKIE,
        ),
    );
    Ok(resp)
}

/// Parse the `YYYY-MM-DDTHH:MM[:SS]` value emitted by the browser's
/// `<input type="datetime-local">` widget into a `DateTime<Utc>`.
///
/// The widget has no timezone — the browser returns local-wall-clock
/// digits. We interpret them as UTC so admin values round-trip
/// unambiguously; a future widget layer can surface the user's timezone
/// explicitly when that becomes necessary.
///
/// Called from `#[derive(RustioAdmin)]`-generated `from_form` bodies via
/// `::rustio_core::admin::parse_datetime_local`. The generated code
/// trims its input before calling; this function is strict and does
/// **not** silently trim, so misuse (calling with unclean input) fails
/// loudly rather than succeeding unpredictably.
pub fn parse_datetime_local(raw: &str) -> Result<DateTime<Utc>, String> {
    if raw.is_empty() {
        return Err(String::from("date-time value is empty"));
    }
    // Reject leading/trailing whitespace and any embedded timezone
    // marker. `datetime-local` is timezone-free by spec; accepting `Z`
    // or a `+HH:MM` suffix would mean two conflicting notions of
    // "what wall clock is this" — refuse at the boundary.
    if raw.trim_matches(|c: char| c.is_ascii_whitespace()) != raw {
        return Err(format!("`{raw}` has surrounding whitespace"));
    }
    if raw.ends_with('Z') || raw.contains('+') || (raw.matches('-').count() > 2) {
        return Err(format!(
            "`{raw}` looks like a timezoned date-time; expected YYYY-MM-DDTHH:MM"
        ));
    }

    // Browsers vary on whether seconds are included. Try both, longest
    // first, so `:SS` is preferred when present.
    let parsed = NaiveDateTime::parse_from_str(raw, "%Y-%m-%dT%H:%M:%S")
        .or_else(|_| NaiveDateTime::parse_from_str(raw, "%Y-%m-%dT%H:%M"))
        .map_err(|_| format!("`{raw}` is not a valid date-time"))?;
    match Utc.from_local_datetime(&parsed) {
        chrono::LocalResult::Single(dt) => Ok(dt),
        // UTC has no DST, so ambiguous/none outcomes shouldn't happen;
        // defend against it anyway rather than unwrap.
        _ => Err(format!("`{raw}` could not be interpreted as UTC")),
    }
}

fn escape_html(s: &str) -> String {
    let mut out = String::with_capacity(s.len());
    for ch in s.chars() {
        match ch {
            '&' => out.push_str("&amp;"),
            '<' => out.push_str("&lt;"),
            '>' => out.push_str("&gt;"),
            '"' => out.push_str("&quot;"),
            '\'' => out.push_str("&#39;"),
            c => out.push(c),
        }
    }
    out
}

const ADMIN_CSS: &str = r#"
*, *::before, *::after { box-sizing: border-box; }
body { font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif;
  background: #fafafa; color: #222; margin: 0; }
header { background: #222; color: white; padding: 1rem 2rem; display: flex; align-items: center; justify-content: space-between; }
header h1 { margin: 0; font-size: 1.1rem; font-weight: 600; letter-spacing: 0.02em; }
header h1 a { color: inherit; text-decoration: none; }
header h1 a:hover { opacity: 0.9; }
header .header-logout { margin: 0; }
header .header-logout button { background: transparent; color: #d8d8dc; border: 1px solid #444; padding: 0.35rem 0.75rem; font-size: 0.85rem; border-radius: 4px; cursor: pointer; }
header .header-logout button:hover { background: #2f2f33; color: white; }
ul.admin-index { list-style: none; padding: 0; margin: 0; display: grid; gap: 0.5rem; }
ul.admin-index li { background: white; border-radius: 6px; box-shadow: 0 1px 3px rgba(0,0,0,0.04); }
ul.admin-index li a { display: flex; justify-content: space-between; align-items: center; padding: 0.9rem 1.1rem; text-decoration: none; color: #222; }
ul.admin-index li a:hover { background: #f4f4f5; }
ul.admin-index li .label { font-weight: 600; }
ul.admin-index li .path { color: #888; font-family: ui-monospace, SFMono-Regular, Menlo, monospace; font-size: 0.85rem; }
p.empty { color: #666; }
p.empty code { background: #f0f0f2; padding: 0.1rem 0.35rem; border-radius: 3px; font-size: 0.9em; }
.auth-error { text-align: center; padding: 3rem 2rem; max-width: 36rem; margin: 0 auto; }
.auth-error .status { font-size: 3rem; font-weight: 700; color: #b42318; line-height: 1; }
.auth-error .heading { font-size: 1.15rem; margin: 0.5rem 0 1.5rem; font-weight: 600; color: #222; }
.auth-error .hint { background: #fff7ed; border: 1px solid #fed7aa; color: #9a3412; padding: 0.85rem 1rem; border-radius: 6px; text-align: left; font-size: 0.92rem; line-height: 1.5; }
.auth-error .hint code { background: #fdefe0; color: #7c2d12; padding: 0.1rem 0.35rem; border-radius: 3px; font-size: 0.9em; display: inline-block; }
.auth-error form.inline { margin-top: 1rem; }
.auth-error form.inline button.secondary { background: transparent; border: 1px solid #d0d0d4; color: #222; }
.auth-card { max-width: 22rem; margin: 2.5rem auto; padding: 2rem; background: white; border-radius: 8px; box-shadow: 0 4px 20px rgba(0,0,0,0.05); }
.auth-card h2 { margin: 0 0 1.25rem; font-size: 1.25rem; }
.auth-card label { display: block; margin: 0 0 0.9rem; }
.auth-card label span { display: block; font-weight: 500; margin-bottom: 0.25rem; font-size: 0.9rem; }
.auth-card input[type=password] { width: 100%; padding: 0.55rem 0.75rem; border: 1px solid #d0d0d4; border-radius: 4px; font: inherit; }
.auth-card button[type=submit] { width: 100%; padding: 0.6rem 1rem; background: #222; color: white; border: none; border-radius: 4px; font: inherit; cursor: pointer; }
.auth-card button[type=submit]:hover { background: #000; }
.auth-card .error { background: #fef2f2; color: #991b1b; border: 1px solid #fecaca; padding: 0.6rem 0.8rem; border-radius: 4px; margin: 0 0 0.9rem; font-size: 0.9rem; }
.auth-card .hint { color: #666; font-size: 0.85rem; margin: 1rem 0 0; line-height: 1.5; }
.auth-card .hint code { background: #f0f0f2; padding: 0.1rem 0.3rem; border-radius: 3px; font-size: 0.85em; }
main { padding: 2rem; max-width: 60rem; margin: 0 auto; }
h2 { margin: 0; }
.toolbar { display: flex; align-items: center; justify-content: space-between; margin-bottom: 1.5rem; }
table { border-collapse: collapse; width: 100%; background: white; border-radius: 6px; overflow: hidden;
  box-shadow: 0 1px 3px rgba(0,0,0,0.04); }
th, td { text-align: left; padding: 0.6rem 0.9rem; border-bottom: 1px solid #eee; font-size: 0.95rem; }
th { background: #f4f4f5; font-weight: 600; }
tbody tr:last-child td { border-bottom: none; }
td.actions { display: flex; gap: 0.5rem; align-items: center; }
td.actions form { margin: 0; display: inline; }
a { color: #0366d6; text-decoration: none; }
a:hover { text-decoration: underline; }
label { display: block; margin-bottom: 1rem; }
label span { display: block; font-weight: 500; margin-bottom: 0.25rem; font-size: 0.9rem; }
input[type=text], input[type=number] { padding: 0.5rem 0.75rem; border: 1px solid #d0d0d4;
  border-radius: 4px; width: 24rem; max-width: 100%; font: inherit; }
input[type=checkbox] { transform: scale(1.1); }
button, .button { padding: 0.5rem 1rem; background: #222; color: white; border: none;
  border-radius: 4px; cursor: pointer; font: inherit; text-decoration: none; display: inline-block; }
button:hover, .button:hover { background: #000; text-decoration: none; }
button.danger { background: #b42318; }
button.danger:hover { background: #8a1c12; }
.form-actions { display: flex; gap: 0.5rem; align-items: center; margin-top: 1rem; }
.form-actions .cancel { color: #666; }
"#;

#[cfg(test)]
mod tests {
    use super::*;
    use chrono::Timelike;

    #[test]
    fn escape_html_escapes_dangerous_chars() {
        assert_eq!(
            escape_html("<script>alert(\"xss\")</script>"),
            "&lt;script&gt;alert(&quot;xss&quot;)&lt;/script&gt;"
        );
        assert_eq!(escape_html("a & b"), "a &amp; b");
        assert_eq!(escape_html("it's"), "it&#39;s");
    }

    // --- DateTime parsing edge cases ------------------------------------

    #[test]
    fn parse_datetime_local_accepts_minute_precision() {
        let dt = parse_datetime_local("2026-04-18T10:12").unwrap();
        assert_eq!(dt.to_rfc3339(), "2026-04-18T10:12:00+00:00");
        // UTC enforcement: `to_rfc3339` encodes the offset and we insist
        // it's zero. The in-memory offset type is `Utc` by construction
        // (return type is `DateTime<Utc>`), but the string shape is the
        // external guarantee callers observe.
        assert!(dt.to_rfc3339().ends_with("+00:00"));
    }

    #[test]
    fn parse_datetime_local_accepts_second_precision() {
        let dt = parse_datetime_local("2026-04-18T10:12:33").unwrap();
        assert_eq!(dt.to_rfc3339(), "2026-04-18T10:12:33+00:00");
    }

    #[test]
    fn parse_datetime_local_rejects_empty_string() {
        assert!(parse_datetime_local("").is_err());
    }

    #[test]
    fn parse_datetime_local_rejects_free_text() {
        assert!(parse_datetime_local("tomorrow at noon").is_err());
    }

    #[test]
    fn parse_datetime_local_rejects_partial_date() {
        // Missing the time half — common copy-paste mistake.
        assert!(parse_datetime_local("2026-04-18").is_err());
    }

    #[test]
    fn parse_datetime_local_rejects_out_of_range_date() {
        // Calendar-invalid: there's no 13th month.
        assert!(parse_datetime_local("2026-13-01T00:00").is_err());
        // Calendar-invalid: April doesn't have a 31st.
        assert!(parse_datetime_local("2026-04-31T00:00").is_err());
    }

    #[test]
    fn parse_datetime_local_rejects_out_of_range_time() {
        assert!(parse_datetime_local("2026-04-18T25:00").is_err());
        assert!(parse_datetime_local("2026-04-18T10:99").is_err());
    }

    #[test]
    fn parse_datetime_local_rejects_surrounding_whitespace() {
        // Trimming is the caller's responsibility — the macro-generated
        // from_form code calls .trim() before us. This test pins the
        // boundary so no one adds implicit trimming here without thinking.
        assert!(parse_datetime_local(" 2026-04-18T10:12").is_err());
        assert!(parse_datetime_local("2026-04-18T10:12 ").is_err());
    }

    #[test]
    fn parse_datetime_local_rejects_timezone_suffix() {
        // `datetime-local` is explicitly timezone-free by spec. Inputs
        // carrying `Z`, `+00:00`, or RFC3339 shape must be refused so
        // callers can't smuggle a second timezone source.
        assert!(parse_datetime_local("2026-04-18T10:12Z").is_err());
        assert!(parse_datetime_local("2026-04-18T10:12:00+00:00").is_err());
    }

    // --- Admin rendering of field widgets --------------------------------
    //
    // These tests pin the contract the schema.nullable flag depends on:
    //   · nullable fields render WITHOUT `required`
    //   · non-nullable, non-bool fields render WITH `required`
    //   · DateTime renders as `<input type="datetime-local">`
    //   · a None on a nullable field renders an empty value and does not
    //     panic through any path
    //
    // Uses a stand-alone type because we need to drive `render_field`
    // directly; the full Model + ORM plumbing isn't relevant here.

    struct Widgety;
    impl crate::orm::Model for Widgety {
        const TABLE: &'static str = "widgety";
        const COLUMNS: &'static [&'static str] = &["id"];
        const INSERT_COLUMNS: &'static [&'static str] = &[];
        fn id(&self) -> i64 {
            0
        }
        fn from_row(_: crate::orm::Row<'_>) -> Result<Self, Error> {
            unimplemented!()
        }
        fn insert_values(&self) -> Vec<crate::orm::Value> {
            Vec::new()
        }
    }
    impl AdminModel for Widgety {
        const ADMIN_NAME: &'static str = "widgety";
        const DISPLAY_NAME: &'static str = "Widgety";
        const FIELDS: &'static [AdminField] = &[];
        fn field_display(&self, name: &str) -> Option<String> {
            // Simulates a Some-wrapped value for "filled" and an
            // explicit None for "empty".
            match name {
                "filled" => Some(String::from("2026-04-18T10:12")),
                "empty" => Some(String::new()),
                _ => None,
            }
        }
        fn from_form(_: &FormData, _: Option<i64>) -> Result<Self, Error> {
            unimplemented!()
        }
    }

    fn string_field(name: &'static str, nullable: bool) -> AdminField {
        AdminField {
            name,
            ty: FieldType::String,
            editable: true,
            nullable,
        }
    }

    fn datetime_field(name: &'static str, nullable: bool) -> AdminField {
        AdminField {
            name,
            ty: FieldType::DateTime,
            editable: true,
            nullable,
        }
    }

    #[test]
    fn nullable_string_field_omits_required_attribute() {
        let f = string_field("note", true);
        let html = render_field::<Widgety>(&f, None);
        assert!(!html.contains("required"), "html was: {html}");
    }

    #[test]
    fn non_nullable_string_field_marks_required() {
        let f = string_field("title", false);
        let html = render_field::<Widgety>(&f, None);
        assert!(html.contains("required"), "html was: {html}");
    }

    #[test]
    fn bool_field_never_marks_required() {
        // Checkboxes have no "unset" UI; the render code must not mark
        // them required regardless of nullability.
        let f = AdminField {
            name: "flag",
            ty: FieldType::Bool,
            editable: true,
            nullable: false,
        };
        let html = render_field::<Widgety>(&f, None);
        assert!(!html.contains("required"), "html was: {html}");
    }

    #[test]
    fn datetime_field_uses_datetime_local_input() {
        let f = datetime_field("starts_at", false);
        let html = render_field::<Widgety>(&f, None);
        assert!(
            html.contains(r#"type="datetime-local""#),
            "html was: {html}"
        );
    }

    #[test]
    fn datetime_field_renders_existing_value() {
        let f = datetime_field("filled", true);
        let html = render_field::<Widgety>(&f, Some(&Widgety));
        assert!(
            html.contains(r#"value="2026-04-18T10:12""#),
            "html was: {html}"
        );
    }

    #[test]
    fn nullable_field_with_none_value_does_not_panic() {
        // `field_display` returns `Some("")` for a None value; the
        // renderer must produce a valid empty input without panicking.
        let f = string_field("empty", true);
        let html = render_field::<Widgety>(&f, Some(&Widgety));
        assert!(html.contains(r#"value="""#));
        assert!(!html.contains("required"));
    }

    #[test]
    fn field_display_returning_none_renders_empty_value() {
        // Simulates `field_display(name)` returning `None` (unknown
        // field): the renderer must default to empty-string rather
        // than panicking.
        let f = string_field("unknown_field", false);
        let html = render_field::<Widgety>(&f, Some(&Widgety));
        assert!(html.contains(r#"value="""#));
    }

    #[test]
    fn parse_datetime_local_enforces_utc_for_every_valid_input() {
        // Quick property-style check: many valid inputs, all UTC.
        let inputs = [
            "2000-01-01T00:00",
            "2026-04-18T10:12",
            "2026-04-18T10:12:33",
            "2099-12-31T23:59",
        ];
        for raw in inputs {
            let dt = parse_datetime_local(raw).unwrap_or_else(|e| panic!("`{raw}`: {e}"));
            assert!(
                dt.to_rfc3339().ends_with("+00:00"),
                "non-UTC offset in output for `{raw}`: {}",
                dt.to_rfc3339(),
            );
            assert!(
                dt.nanosecond() == 0,
                "unexpected sub-second part for `{raw}`"
            );
        }
    }
}
